"""
backend/api/exec_pdf.py — server-rendered Executive Summary PDF (fpdf2).

Replaces the earlier print-the-webpage approach the HOD rejected: every table
is measured and laid out to fit the printable area exactly (content can never
run off the page edges), rows never split across a page boundary, table
headers repeat after every page break, and each page carries a letterhead
strip + "Page X of Y" footer. A4 landscape, core Helvetica; all text passes
through reports._latin so non-latin glyphs degrade instead of crashing.
"""
from __future__ import annotations

from fpdf import FPDF

from .reports import _latin

# Palette (matches the web app / xlsx exports: navy #0A192F + AntD blue).
_NAVY = (10, 25, 47)
_ACCENT = (24, 144, 255)
_ZEBRA = (245, 247, 250)
_BORDER = (208, 213, 221)
_MUTED = (100, 110, 125)
_GREEN = (56, 158, 13)
_RED = (207, 19, 34)
_BOX_BG = (247, 249, 252)

_ROW_H = 6.2
_HDR_H = 7.0


def _fmt(v) -> str:
    """Human number formatting: ints plain, floats trimmed to ≤2 dp with
    thousands separators; everything else str()."""
    if v is None:
        return ""
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, int):
        return f"{v:,}"
    if isinstance(v, float):
        s = f"{v:,.2f}"
        return s.rstrip("0").rstrip(".") if "." in s else s
    return str(v)


class _ExecPDF(FPDF):
    """A4-landscape report page with a repeating letterhead + numbered footer."""

    def __init__(self, *, site: str, period: str, username: str):
        super().__init__(orientation="L", unit="mm", format="A4")
        self.site_label = site
        self.period_label = period
        self.username = username
        self.set_margins(12, 12, 12)
        self.set_auto_page_break(auto=True, margin=16)
        self.alias_nb_pages()

    def header(self):
        if self.page_no() == 1:
            return  # page 1 draws its own cover band
        self.set_fill_color(*_NAVY)
        self.rect(0, 0, self.w, 9, style="F")
        self.set_y(2)
        self.set_font("helvetica", "B", 8)
        self.set_text_color(255, 255, 255)
        self.cell(0, 5, _latin(f"EXECUTIVE SUMMARY  -  {self.site_label}  -  {self.period_label}"),
                  align="L")
        self.set_y(13)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-11)
        self.set_draw_color(*_BORDER)
        self.set_line_width(0.2)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.set_font("helvetica", "", 7)
        self.set_text_color(*_MUTED)
        self.cell(0, 6, _latin(f"GI Hub - Executive Summary  -  generated by {self.username}"),
                  align="L")
        self.cell(0, 6, f"Page {self.page_no()} of {{nb}}", align="R")


def _fit(pdf: FPDF, txt: str, w: float) -> str:
    """Truncate txt (with a trailing '..') so it always fits inside width w."""
    t = _latin(str(txt))
    if pdf.get_string_width(t) <= w - 2:
        return t
    while t and pdf.get_string_width(t + "..") > w - 2:
        t = t[:-1]
    return t + ".."


def _col_widths(pdf: FPDF, columns: list[str], rows: list[list], font_size: float) -> list[float]:
    """Content-proportional widths that sum exactly to the printable width, so
    a table can never overflow the page. Sampled over the first 300 rows."""
    pdf.set_font("helvetica", "", font_size)
    needs = []
    for i, col in enumerate(columns):
        w = pdf.get_string_width(_latin(str(col))) * 1.15  # bold header allowance
        for r in rows[:300]:
            w = max(w, pdf.get_string_width(_latin(_fmt(r[i]))))
        needs.append(min(max(w + 3.0, 13.0), 90.0))
    total = sum(needs)
    epw = pdf.w - pdf.l_margin - pdf.r_margin
    return [n * epw / total for n in needs] if total > 0 else [epw / len(columns)] * len(columns)


def _ensure_room(pdf: FPDF, needed: float):
    if pdf.get_y() + needed > pdf.page_break_trigger:
        pdf.add_page()


def _section_title(pdf: FPDF, title: str, sub: str = ""):
    _ensure_room(pdf, 10 + _HDR_H + 2 * _ROW_H)  # keep the heading with its table
    pdf.ln(3)
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(*_NAVY)
    pdf.cell(0, 7, _latin(title), new_x="LMARGIN", new_y="NEXT")
    y = pdf.get_y()
    pdf.set_fill_color(*_ACCENT)
    pdf.rect(pdf.l_margin, y, 22, 0.8, style="F")
    pdf.set_y(y + 2.0)
    if sub:
        pdf.set_font("helvetica", "", 7.5)
        pdf.set_text_color(*_MUTED)
        pdf.cell(0, 4.5, _latin(sub), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)


def _table_header(pdf: FPDF, columns: list[str], widths: list[float]):
    pdf.set_font("helvetica", "B", 7)
    pdf.set_fill_color(*_NAVY)
    pdf.set_text_color(255, 255, 255)
    pdf.set_draw_color(*_BORDER)
    for col, w in zip(columns, widths):
        pdf.cell(w, _HDR_H, _fit(pdf, str(col).replace("_", " "), w), border=1,
                 fill=True, align="C")
    pdf.ln(_HDR_H)
    pdf.set_text_color(0, 0, 0)


_NUMERIC = (int, float)


def _table(pdf: FPDF, title: str, columns: list[str], rows: list[list],
           sub: str = "", font_size: float = 7.0):
    """Full-width bordered table: measured columns, zebra rows, repeated
    header after page breaks, rows never split across pages."""
    _section_title(pdf, title, sub)
    if not rows:
        pdf.set_font("helvetica", "I", 8)
        pdf.set_text_color(*_MUTED)
        pdf.cell(0, 6, "No data for this period.", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        return
    widths = _col_widths(pdf, columns, rows, font_size)
    aligns = ["R" if all(isinstance(r[i], _NUMERIC) or r[i] in (None, "")
                         for r in rows[:50]) else "L"
              for i in range(len(columns))]
    _table_header(pdf, columns, widths)
    pdf.set_font("helvetica", "", font_size)
    for n, row in enumerate(rows):
        if pdf.get_y() + _ROW_H > pdf.page_break_trigger:
            pdf.add_page()
            _table_header(pdf, columns, widths)
            pdf.set_font("helvetica", "", font_size)
        fill = n % 2 == 1
        if fill:
            pdf.set_fill_color(*_ZEBRA)
        for v, w, a in zip(row, widths, aligns):
            pdf.cell(w, _ROW_H, _fit(pdf, _fmt(v), w), border=1, fill=fill, align=a)
        pdf.ln(_ROW_H)
    pdf.set_font("helvetica", "", 6.5)
    pdf.set_text_color(*_MUTED)
    pdf.cell(0, 4.5, f"{len(rows):,} row(s)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)


def _kpi_box(pdf: FPDF, x: float, y: float, w: float, h: float,
             label: str, value: str, sub: str, sub_color=None):
    pdf.set_fill_color(*_BOX_BG)
    pdf.set_draw_color(*_BORDER)
    pdf.rect(x, y, w, h, style="FD")
    pdf.set_fill_color(*_ACCENT)
    pdf.rect(x, y, w, 1.0, style="F")
    pdf.set_xy(x + 2.5, y + 2.6)
    pdf.set_font("helvetica", "B", 6.5)
    pdf.set_text_color(*_MUTED)
    pdf.cell(w - 5, 3.5, _fit(pdf, label.upper(), w - 5))
    pdf.set_xy(x + 2.5, y + 6.6)
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(*_NAVY)
    pdf.cell(w - 5, 7, _fit(pdf, value, w - 5))
    pdf.set_xy(x + 2.5, y + 14.2)
    pdf.set_font("helvetica", "", 6.5)
    pdf.set_text_color(*(sub_color or _MUTED))
    pdf.cell(w - 5, 3.5, _fit(pdf, sub, w - 5))
    pdf.set_text_color(0, 0, 0)


def _delta_sub(k: dict, qty_key: str, prev_key: str, extra: str = "") -> tuple[str, tuple]:
    delta = k.get("delta_pct")
    if delta is None:
        return (extra or "no prior-window data", _MUTED)
    arrow = "+" if delta >= 0 else ""
    color = _GREEN if delta >= 0 else _RED
    txt = f"{arrow}{delta:g}% vs prev ({_fmt(k.get(prev_key))})"
    if extra:
        txt = f"{extra}  -  {txt}"
    return (txt, color)


def render_exec_pdf(d: dict, *, site: str | None, username: str) -> bytes:
    """d = exec_summary._build_summary payload → styled multi-page PDF bytes."""
    site_label = site or "ALL SITES"
    period = (d["date_from"] if d["date_from"] == d["date_to"]
              else f'{d["date_from"]} to {d["date_to"]}')
    pdf = _ExecPDF(site=site_label, period=period, username=username)
    pdf.add_page()

    # ── cover band ───────────────────────────────────────────────────────────
    pdf.set_fill_color(*_NAVY)
    pdf.rect(0, 0, pdf.w, 26, style="F")
    pdf.set_fill_color(*_ACCENT)
    pdf.rect(0, 26, pdf.w, 1.1, style="F")
    pdf.set_xy(pdf.l_margin, 6)
    pdf.set_font("helvetica", "B", 19)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 9, "EXECUTIVE SUMMARY", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 9.5)
    pdf.cell(0, 6, _latin(f"GI Hub  -  {site_label}  -  {period} ({d['days']} day(s))"))
    pdf.set_font("helvetica", "", 7.5)
    pdf.set_xy(pdf.l_margin, 6)
    pdf.cell(0, 5, _latin(f"Generated {d['generated_at']} by {username}"), align="R")
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(31)

    # ── KPI dashboard (6 boxes) ──────────────────────────────────────────────
    k = d["kpis"]
    epw = pdf.w - pdf.l_margin - pdf.r_margin
    gap, box_h = 3.0, 19.0
    bw = (epw - 5 * gap) / 6
    y0 = pdf.get_y()
    mp = k["manpower"]
    boxes = []
    for key, label in (("receipts", "Receipts (qty)"),
                       ("consumption", "Consumption (qty)"),
                       ("returns", "Returns (qty)")):
        sub, color = _delta_sub(k[key], "qty", "prev_qty", f'{k[key]["count"]:,} entries')
        boxes.append((label, _fmt(k[key]["qty"]), sub, color))
    sub, color = _delta_sub(k["sqm_done"], "total", "prev")
    boxes.append(("SQM Done", _fmt(k["sqm_done"]["total"]), sub, color))
    sub, color = _delta_sub(k["man_hours"], "total", "prev")
    boxes.append(("Man-Hours", _fmt(k["man_hours"]["total"]), sub, color))
    boxes.append(("Manpower", f'{mp["present"]} / {mp["absent"]}',
                  f'present / absent of {mp["active_total"]} active', _MUTED))
    for i, (label, value, sub, color) in enumerate(boxes):
        _kpi_box(pdf, pdf.l_margin + i * (bw + gap), y0, bw, box_h, label, value, sub, color)
    pdf.set_y(y0 + box_h + 2)

    # ── actions & pipeline at a glance (4-column key/value grid) ────────────
    a_t, a_p = d["actions"]["taken"], d["actions"]["pending"]
    dnq = a_p["dn_queue"]
    glance = [
        ("PRs raised in period", d["pr_status"]["raised_in_period"],
         "Receipts posted", a_t["receipts_posted"]),
        ("Open POs (overdue)", f'{d["po_status"]["open"]} ({d["po_status"]["overdue"]})',
         "Issues approved", a_t["issues_approved"]),
        ("Pending entry approvals", a_p["entry_approvals"],
         "Returns processed", a_t["returns_processed"]),
        ("DN queue (logistics / HOD)",
         f'{dnq.get("pending_logistics", 0)} / {dnq.get("pending_hod", 0)}',
         "Entries rejected", a_t["entries_rejected"]),
        ("Pending SMRs / draft PRs", f'{a_p["smr_pending"]} / {a_p["draft_prs"]}',
         "DN decisions", a_t["dn_decisions"]),
    ]
    _section_title(pdf, "Actions & Pipeline at a Glance",
                   "left: pending / pipeline - right: actions taken in the period")
    kw, vw = epw * 0.30, epw * 0.20
    pdf.set_draw_color(*_BORDER)
    for n, (k1, v1, k2, v2) in enumerate(glance):
        fill = n % 2 == 1
        if fill:
            pdf.set_fill_color(*_ZEBRA)
        pdf.set_font("helvetica", "", 8)
        pdf.cell(kw, _ROW_H, _fit(pdf, k1, kw), border=1, fill=fill)
        pdf.set_font("helvetica", "B", 8)
        pdf.cell(vw, _ROW_H, _fit(pdf, _fmt(v1), vw), border=1, fill=fill, align="R")
        pdf.set_font("helvetica", "", 8)
        pdf.cell(kw, _ROW_H, _fit(pdf, k2, kw), border=1, fill=fill)
        pdf.set_font("helvetica", "B", 8)
        pdf.cell(vw, _ROW_H, _fit(pdf, _fmt(v2), vw), border=1, fill=fill, align="R")
        pdf.ln(_ROW_H)

    def rows_of(items: list[dict], cols: list[str]) -> list[list]:
        return [[r.get(c) for c in cols] for r in items]

    # ── detail sections (same shapes as the xlsx sheets) ─────────────────────
    _table(pdf, "Material Receipts",
           ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM",
            "Supplier", "Lot_Number", "PR_Number", "Site_ID"],
           rows_of(d["receipts_detail"],
                   ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM",
                    "Supplier", "Lot_Number", "PR_Number", "Site_ID"]))
    _table(pdf, "Material Consumption",
           ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM",
            "Issued_To", "Work_Type", "WBS", "Lot_Number", "Site_ID"],
           rows_of(d["consumption_detail"],
                   ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM",
                    "Issued_To", "Work_Type", "WBS", "Lot_Number", "Site_ID"]))
    _table(pdf, "Material Returns",
           ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM", "Site_ID"],
           rows_of(d["returns_detail"],
                   ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM", "Site_ID"]))
    _table(pdf, "SQM Done (Production)",
           ["Work_Date", "Equipment_Tag", "System_Code", "SQM_Done"],
           rows_of(d["sqm_detail"], ["Work_Date", "Equipment_Tag", "System_Code", "SQM_Done"]))
    _table(pdf, "Manpower Present",
           ["Employee_Code", "Name", "Designation", "Worker_Type",
            "Hours", "OT_Hours", "Allocated_SQM"],
           rows_of(d["manpower"]["present"],
                   ["Employee_Code", "Name", "Designation", "Worker_Type",
                    "Hours", "OT_Hours", "Allocated_SQM"]),
           sub=f'{k["manpower"]["present"]} of {k["manpower"]["active_total"]} active employees')
    _table(pdf, "Manpower Absent",
           ["Employee_Code", "Name", "Designation", "Worker_Type"],
           rows_of(d["manpower"]["absent"],
                   ["Employee_Code", "Name", "Designation", "Worker_Type"]),
           sub="active employees with no timesheet entry in the period")
    _table(pdf, "PR Status (open pipeline by state)", ["State", "PRs"],
           [[r["state"], r["n"]] for r in d["pr_status"]["open_by_state"]],
           sub=f'{d["pr_status"]["raised_in_period"]} PR(s) raised in the period')
    _table(pdf, "PO Status", ["Status", "POs"],
           [[r["status"], r["n"]] for r in d["po_status"]["by_status"]],
           sub=f'{d["po_status"]["open"]} open - {d["po_status"]["overdue"]} overdue')
    _table(pdf, "Delivery Plan - Delivery Notes in Flight",
           ["DN_Number", "PO_Number", "Warehouse_ID", "Site_ID", "status",
            "DN_Date", "Vehicle_No", "Driver_Name"],
           rows_of(d["delivery_plan"]["dn_in_flight"],
                   ["DN_Number", "PO_Number", "Warehouse_ID", "Site_ID", "status",
                    "DN_Date", "Vehicle_No", "Driver_Name"]))
    _table(pdf, "Delivery Plan - Upcoming Deliveries",
           ["PO_Number", "Warehouse_ID", "Expected_Delivery", "status",
            "Site_ID", "Vendor_Name"],
           rows_of(d["delivery_plan"]["upcoming_deliveries"],
                   ["PO_Number", "Warehouse_ID", "Expected_Delivery", "status",
                    "Site_ID", "Vendor_Name"]),
           sub=f'expected up to {d["delivery_plan"]["window_to"]}')
    _table(pdf, "Achievable SQM per Equipment (available material)",
           ["Equipment_Tag", "Name", "Remaining_SQM", "Achievable_SQM",
            "Coverage_Pct", "Bottleneck"],
           rows_of(d["sqm_capacity"]["per_equipment"],
                   ["Equipment_Tag", "Name", "Remaining_SQM", "Achievable_SQM",
                    "Coverage_Pct", "Bottleneck"]),
           sub="SME engine, read-only - strict bottleneck: the least-covered material caps each unit")
    _table(pdf, "Achievable SQM per System Code",
           ["System_Code", "System_Name", "Remaining_SQM", "Achievable_SQM", "Coverage_Pct"],
           rows_of(d["sqm_capacity"]["per_system"],
                   ["System_Code", "System_Name", "Remaining_SQM", "Achievable_SQM",
                    "Coverage_Pct"]))
    _table(pdf, "Cross-Site Enquiries",
           ["id", "requesting_site", "target_site", "SAP_Code", "requested_qty",
            "available_qty", "status", "requested_by", "created"],
           rows_of(d["cross_site"],
                   ["id", "requesting_site", "target_site", "SAP_Code", "requested_qty",
                    "available_qty", "status", "requested_by", "created"]))

    return bytes(pdf.output())
