"""
backend/api/exec_pdf.py — server-rendered Executive Summary PDF (fpdf2).

Replaces the earlier print-the-webpage approach the HOD rejected: every table
is measured and laid out to fit the printable area exactly (content can never
run off the page edges), rows never split across a page boundary, table
headers repeat after every page break, and each page carries a letterhead
strip + "Page X of Y" footer. A4 landscape, core Helvetica; all text passes
through reports._latin so non-latin glyphs degrade instead of crashing.
"""
from __future__ import annotations

from fpdf import FPDF

from .reports import _latin

# Palette (matches the web app / xlsx exports: navy #0A192F + AntD blue).
_NAVY = (10, 25, 47)
_ACCENT = (24, 144, 255)
_ZEBRA = (245, 247, 250)
_BORDER = (208, 213, 221)
_MUTED = (100, 110, 125)
_GREEN = (56, 158, 13)
_RED = (207, 19, 34)
_BOX_BG = (247, 249, 252)

_ROW_H = 6.2
_HDR_H = 7.0


def _fmt(v) -> str:
    """Human number formatting: ints plain, floats trimmed to ≤2 dp with
    thousands separators; everything else str()."""
    if v is None:
        return ""
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, int):
        return f"{v:,}"
    if isinstance(v, float):
        s = f"{v:,.2f}"
        return s.rstrip("0").rstrip(".") if "." in s else s
    return str(v)


class _ExecPDF(FPDF):
    """A4-landscape report page with a repeating letterhead + numbered footer."""

    def __init__(self, *, site: str, period: str, username: str):
        super().__init__(orientation="L", unit="mm", format="A4")
        self.site_label = site
        self.period_label = period
        self.username = username
        self.set_margins(12, 12, 12)
        self.set_auto_page_break(auto=True, margin=16)
        self.alias_nb_pages()

    def header(self):
        if self.page_no() == 1:
            return  # page 1 draws its own cover band
        self.set_fill_color(*_NAVY)
        self.rect(0, 0, self.w, 9, style="F")
        self.set_y(2)
        self.set_font("helvetica", "B", 8)
        self.set_text_color(255, 255, 255)
        self.cell(0, 5, _latin(f"EXECUTIVE SUMMARY  -  {self.site_label}  -  {self.period_label}"),
                  align="L")
        self.set_y(13)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-11)
        self.set_draw_color(*_BORDER)
        self.set_line_width(0.2)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.set_font("helvetica", "", 7)
        self.set_text_color(*_MUTED)
        self.cell(0, 6, _latin(f"GI Hub - Executive Summary  -  generated by {self.username}"),
                  align="L")
        self.cell(0, 6, f"Page {self.page_no()} of {{nb}}", align="R")


def _fit(pdf: FPDF, txt: str, w: float) -> str:
    """Truncate txt (with a trailing '..') so it always fits inside width w."""
    t = _latin(str(txt))
    if pdf.get_string_width(t) <= w - 2:
        return t
    while t and pdf.get_string_width(t + "..") > w - 2:
        t = t[:-1]
    return t + ".."


def _ensure_room(pdf: FPDF, needed: float):
    if pdf.get_y() + needed > pdf.page_break_trigger:
        pdf.add_page()


def _section_title(pdf: FPDF, title: str, sub: str = ""):
    _ensure_room(pdf, 10 + _HDR_H + 2 * _ROW_H)  # keep the heading with its table
    pdf.ln(3)
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(*_NAVY)
    pdf.cell(0, 7, _latin(title), new_x="LMARGIN", new_y="NEXT")
    y = pdf.get_y()
    pdf.set_fill_color(*_ACCENT)
    pdf.rect(pdf.l_margin, y, 22, 0.8, style="F")
    pdf.set_y(y + 2.0)
    if sub:
        pdf.set_font("helvetica", "", 7.5)
        pdf.set_text_color(*_MUTED)
        pdf.cell(0, 4.5, _latin(sub), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)


def _table(pdf: FPDF, title: str, columns: list[str], rows: list[list],
           sub: str = "", font_size: float = 7.0):
    """Full-width bordered table, rendered by the shared engine in
    `pdf_tables`: measured proportional columns, WRAPPED cells, zebra rows,
    header repeated after every page break, rows never split.

    This used to measure widths here and then `_fit`-truncate anything that
    still did not fit — so a long `Equipment_Description` lost its tail even
    though the layout was otherwise sound. Wrapping keeps the whole value.
    """
    _section_title(pdf, title, sub)
    from .pdf_tables import draw_table
    draw_table(pdf, columns, rows)


def _kpi_box(pdf: FPDF, x: float, y: float, w: float, h: float,
             label: str, value: str, sub: str, sub_color=None):
    pdf.set_fill_color(*_BOX_BG)
    pdf.set_draw_color(*_BORDER)
    pdf.rect(x, y, w, h, style="FD")
    pdf.set_fill_color(*_ACCENT)
    pdf.rect(x, y, w, 1.0, style="F")
    pdf.set_xy(x + 2.5, y + 2.6)
    pdf.set_font("helvetica", "B", 6.5)
    pdf.set_text_color(*_MUTED)
    pdf.cell(w - 5, 3.5, _fit(pdf, label.upper(), w - 5))
    pdf.set_xy(x + 2.5, y + 6.6)
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(*_NAVY)
    pdf.cell(w - 5, 7, _fit(pdf, value, w - 5))
    pdf.set_xy(x + 2.5, y + 14.2)
    pdf.set_font("helvetica", "", 6.5)
    pdf.set_text_color(*(sub_color or _MUTED))
    pdf.cell(w - 5, 3.5, _fit(pdf, sub, w - 5))
    pdf.set_text_color(0, 0, 0)


def _delta_sub(k: dict, qty_key: str, prev_key: str, extra: str = "") -> tuple[str, tuple]:
    delta = k.get("delta_pct")
    if delta is None:
        return (extra or "no prior-window data", _MUTED)
    arrow = "+" if delta >= 0 else ""
    color = _GREEN if delta >= 0 else _RED
    txt = f"{arrow}{delta:g}% vs prev ({_fmt(k.get(prev_key))})"
    if extra:
        txt = f"{extra}  -  {txt}"
    return (txt, color)


def render_exec_pdf(d: dict, *, site: str | None, username: str) -> bytes:
    """d = exec_summary._build_summary payload → styled multi-page PDF bytes."""
    site_label = site or "ALL SITES"
    period = (d["date_from"] if d["date_from"] == d["date_to"]
              else f'{d["date_from"]} to {d["date_to"]}')
    pdf = _ExecPDF(site=site_label, period=period, username=username)
    pdf.add_page()

    # ── cover band ───────────────────────────────────────────────────────────
    pdf.set_fill_color(*_NAVY)
    pdf.rect(0, 0, pdf.w, 26, style="F")
    pdf.set_fill_color(*_ACCENT)
    pdf.rect(0, 26, pdf.w, 1.1, style="F")
    pdf.set_xy(pdf.l_margin, 6)
    pdf.set_font("helvetica", "B", 19)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 9, "EXECUTIVE SUMMARY", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 9.5)
    pdf.cell(0, 6, _latin(f"GI Hub  -  {site_label}  -  {period} ({d['days']} day(s))"))
    pdf.set_font("helvetica", "", 7.5)
    pdf.set_xy(pdf.l_margin, 6)
    pdf.cell(0, 5, _latin(f"Generated {d['generated_at']} by {username}"), align="R")
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(31)

    # ── KPI dashboard (6 boxes) ──────────────────────────────────────────────
    k = d["kpis"]
    epw = pdf.w - pdf.l_margin - pdf.r_margin
    gap, box_h = 3.0, 19.0
    bw = (epw - 5 * gap) / 6
    y0 = pdf.get_y()
    mp = k["manpower"]
    boxes = []
    for key, label in (("receipts", "Receipts (qty)"),
                       ("consumption", "Consumption (qty)"),
                       ("returns", "Returns (qty)")):
        sub, color = _delta_sub(k[key], "qty", "prev_qty", f'{k[key]["count"]:,} entries')
        boxes.append((label, _fmt(k[key]["qty"]), sub, color))
    sub, color = _delta_sub(k["sqm_done"], "total", "prev")
    boxes.append(("SQM Done", _fmt(k["sqm_done"]["total"]), sub, color))
    sub, color = _delta_sub(k["man_hours"], "total", "prev")
    boxes.append(("Man-Hours", _fmt(k["man_hours"]["total"]), sub, color))
    boxes.append(("Manpower", f'{mp["present"]} / {mp["absent"]}',
                  f'present / absent of {mp["active_total"]} active', _MUTED))
    for i, (label, value, sub, color) in enumerate(boxes):
        _kpi_box(pdf, pdf.l_margin + i * (bw + gap), y0, bw, box_h, label, value, sub, color)
    pdf.set_y(y0 + box_h + 2)

    # ── actions & pipeline at a glance (4-column key/value grid) ────────────
    a_t, a_p = d["actions"]["taken"], d["actions"]["pending"]
    dnq = a_p["dn_queue"]
    glance = [
        ("PRs raised in period", d["pr_status"]["raised_in_period"],
         "Receipts posted", a_t["receipts_posted"]),
        ("Open POs (overdue)", f'{d["po_status"]["open"]} ({d["po_status"]["overdue"]})',
         "Issues approved", a_t["issues_approved"]),
        ("Pending entry approvals", a_p["entry_approvals"],
         "Returns processed", a_t["returns_processed"]),
        ("DN queue (logistics / HOD)",
         f'{dnq.get("pending_logistics", 0)} / {dnq.get("pending_hod", 0)}',
         "Entries rejected", a_t["entries_rejected"]),
        ("Pending SMRs / draft PRs", f'{a_p["smr_pending"]} / {a_p["draft_prs"]}',
         "DN decisions", a_t["dn_decisions"]),
    ]
    _section_title(pdf, "Actions & Pipeline at a Glance",
                   "left: pending / pipeline - right: actions taken in the period")
    kw, vw = epw * 0.30, epw * 0.20
    pdf.set_draw_color(*_BORDER)
    for n, (k1, v1, k2, v2) in enumerate(glance):
        fill = n % 2 == 1
        if fill:
            pdf.set_fill_color(*_ZEBRA)
        pdf.set_font("helvetica", "", 8)
        pdf.cell(kw, _ROW_H, _fit(pdf, k1, kw), border=1, fill=fill)
        pdf.set_font("helvetica", "B", 8)
        pdf.cell(vw, _ROW_H, _fit(pdf, _fmt(v1), vw), border=1, fill=fill, align="R")
        pdf.set_font("helvetica", "", 8)
        pdf.cell(kw, _ROW_H, _fit(pdf, k2, kw), border=1, fill=fill)
        pdf.set_font("helvetica", "B", 8)
        pdf.cell(vw, _ROW_H, _fit(pdf, _fmt(v2), vw), border=1, fill=fill, align="R")
        pdf.ln(_ROW_H)

    def rows_of(items: list[dict], cols: list[str]) -> list[list]:
        return [[r.get(c) for c in cols] for r in items]

    # ── detail sections (same shapes as the xlsx sheets) ─────────────────────
    _table(pdf, "Material Receipts",
           ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM",
            "Supplier", "Lot_Number", "PR_Number", "Site_ID"],
           rows_of(d["receipts_detail"],
                   ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM",
                    "Supplier", "Lot_Number", "PR_Number", "Site_ID"]))
    _table(pdf, "Material Consumption",
           ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM",
            "Issued_To", "Work_Type", "WBS", "Lot_Number", "Site_ID"],
           rows_of(d["consumption_detail"],
                   ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM",
                    "Issued_To", "Work_Type", "WBS", "Lot_Number", "Site_ID"]))
    _table(pdf, "Material Returns",
           ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM", "Site_ID"],
           rows_of(d["returns_detail"],
                   ["Date", "SAP_Code", "Equipment_Description", "Quantity", "UOM", "Site_ID"]))
    _table(pdf, "SQM Done (Production)",
           ["Work_Date", "Equipment_Tag", "System_Code", "SQM_Done", "Remarks"],
           rows_of(d["sqm_detail"], ["Work_Date", "Equipment_Tag", "System_Code", "SQM_Done",
                                     "Remarks"]))
    # Phase 20a — the Surface Shield daily log: what was drawn, the remark as
    # typed in Excel, the SQM, and the HOD's decision (ruling Q20-7).
    ss = d.get("surface_shield") or {}
    sk = ss.get("kpis")
    if sk:
        # the indices below are sme_history.EXPORT_COLUMNS' layout (suite 20A pins it)
        _table(pdf, "Surface Shield Daily Log",
               ["Date", "Section", "Equipment", "System", "Status", "SQM", "SQM in remark",
                "Excel remark", "Decided by", "Reason / justification"],
               [[r[0], r[1], r[2], r[3], r[5], r[6], r[7], r[8], r[12], r[14]]
                for r in ss.get("rows", [])],
               sub=(f'{sk["sqm_approved"]:g} m2 approved · {sk["sqm_pending"]:g} m2 pending HOD · '
                    f'{sk["jobs"]["rejected"]} rejected · {sk["jobs"]["not_filed"]} not yet filed'
                    + (f' · {sk["high_priority_pending"]} high-variance pending'
                       if sk["high_priority_pending"] else "")))
    _table(pdf, "Manpower Present",
           ["Employee_Code", "Name", "Designation", "Worker_Type",
            "Hours", "OT_Hours", "Allocated_SQM"],
           rows_of(d["manpower"]["present"],
                   ["Employee_Code", "Name", "Designation", "Worker_Type",
                    "Hours", "OT_Hours", "Allocated_SQM"]),
           sub=f'{k["manpower"]["present"]} of {k["manpower"]["active_total"]} active employees')
    _table(pdf, "Manpower Absent",
           ["Employee_Code", "Name", "Designation", "Worker_Type"],
           rows_of(d["manpower"]["absent"],
                   ["Employee_Code", "Name", "Designation", "Worker_Type"]),
           sub="active employees with no timesheet entry in the period")
    _table(pdf, "PR Status (open pipeline by state)", ["State", "PRs"],
           [[r["state"], r["n"]] for r in d["pr_status"]["open_by_state"]],
           sub=f'{d["pr_status"]["raised_in_period"]} PR(s) raised in the period')
    _table(pdf, "PO Status", ["Status", "POs"],
           [[r["status"], r["n"]] for r in d["po_status"]["by_status"]],
           sub=f'{d["po_status"]["open"]} open - {d["po_status"]["overdue"]} overdue')
    _table(pdf, "Delivery Plan - Delivery Notes in Flight",
           ["DN_Number", "PO_Number", "Warehouse_ID", "Site_ID", "status",
            "DN_Date", "Vehicle_No", "Driver_Name"],
           rows_of(d["delivery_plan"]["dn_in_flight"],
                   ["DN_Number", "PO_Number", "Warehouse_ID", "Site_ID", "status",
                    "DN_Date", "Vehicle_No", "Driver_Name"]))
    _table(pdf, "Delivery Plan - Upcoming Deliveries",
           ["PO_Number", "Warehouse_ID", "Expected_Delivery", "status",
            "Site_ID", "Vendor_Name"],
           rows_of(d["delivery_plan"]["upcoming_deliveries"],
                   ["PO_Number", "Warehouse_ID", "Expected_Delivery", "status",
                    "Site_ID", "Vendor_Name"]),
           sub=f'expected up to {d["delivery_plan"]["window_to"]}')
    # "Achievable" is PHYSICAL stock (tier 1); "Ordered" is the forecast once
    # open POs land. They are separate columns and never summed together.
    _table(pdf, "Achievable SQM per Equipment (stock ON HAND)",
           ["Equipment_Tag", "Name", "Remaining_SQM", "Achievable_SQM",
            "Ordered_SQM", "Coverage_Pct", "Ordered_Pct", "Bottleneck"],
           rows_of(d["sqm_capacity"]["per_equipment"],
                   ["Equipment_Tag", "Name", "Remaining_SQM", "Achievable_SQM",
                    "Achievable_With_Ordered_SQM", "Coverage_Pct",
                    "Coverage_With_Ordered_Pct", "Bottleneck"]),
           sub="SME engine, read-only - strict bottleneck on PHYSICAL stock; "
               "'Ordered' columns add stock on open purchase orders (forecast only)")
    _table(pdf, "Achievable SQM per System Code (stock ON HAND)",
           ["System_Code", "System_Name", "Remaining_SQM", "Achievable_SQM",
            "Ordered_SQM", "Coverage_Pct", "Ordered_Pct"],
           rows_of(d["sqm_capacity"]["per_system"],
                   ["System_Code", "System_Name", "Remaining_SQM", "Achievable_SQM",
                    "Achievable_With_Ordered_SQM", "Coverage_Pct",
                    "Coverage_With_Ordered_Pct"]))
    _table(pdf, "Cross-Site Enquiries",
           ["id", "requesting_site", "target_site", "SAP_Code", "requested_qty",
            "available_qty", "status", "requested_by", "created"],
           rows_of(d["cross_site"],
                   ["id", "requesting_site", "target_site", "SAP_Code", "requested_qty",
                    "available_qty", "status", "requested_by", "created"]))

    return bytes(pdf.output())


# ─── Track 3 (slice 10b): the valuation & burn brief ─────────────────────────
class _ValuationPDF(_ExecPDF):
    """Same letterhead, different title — one branding implementation.

    ⚠️ SUBCLASSED RATHER THAN COPIED. Two renderers with two copies of the GI
    palette drift the first time somebody adjusts one, and a board pack whose
    two halves are subtly different navies looks like two documents.
    """

    def header(self):
        if self.page_no() == 1:
            return
        self.set_fill_color(*_NAVY)
        self.rect(0, 0, self.w, 9, style="F")
        self.set_y(2)
        self.set_font("helvetica", "B", 8)
        self.set_text_color(255, 255, 255)
        self.cell(0, 5, _latin(f"VALUATION & BURN  -  {self.site_label}  -  "
                               f"{self.period_label}"), align="L")
        self.set_y(13)
        self.set_text_color(0, 0, 0)

    def footer(self):
        # Overridden so a board pack does not carry another report's name in
        # its footer — the inherited one says "Executive Summary".
        self.set_y(-11)
        self.set_draw_color(*_BORDER)
        self.set_line_width(0.2)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.set_font("helvetica", "", 7)
        self.set_text_color(*_MUTED)
        self.cell(0, 6, _latin("GI Hub - Valuation & 30-Day Burn  -  generated "
                               f"by {self.username}"), align="L")
        self.cell(0, 6, f"Page {self.page_no()} of {{nb}}", align="R")


def _money(v, currency: str = "SAR") -> str:
    return f"{currency} {float(v or 0):,.2f}"


def render_valuation_pdf(d: dict, *, username: str) -> bytes:
    """The board brief. A pure function of `services.valuation.build_valuation`.

    ⚠️ THREE THINGS THIS RENDERER WILL NOT DO, each of which would make the
    document read better and be false:

      1. It never prints a single "total stock value" that silently includes
         un-costed lines at zero. The un-costed count is a KPI box of its own
         and a footnote under every table that has one.
      2. It never adds the ERP figures to the SME seed. They are two tables
         with a paragraph between them saying why (rule 1a).
      3. It never prints a months-of-cover figure when the burn is zero. A site
         that consumed nothing has no runway; inventing one out of a division
         by zero is exactly the shape of error suite CO exists for.
    """
    cur = d.get("currency", "SAR")
    stock, burn, sme = d["stock"], d["burn"], d.get("sme") or {}
    site_label = d.get("site") or "All sites"
    period = f"{burn['days']}-day window from {burn['since']}"

    pdf = _ValuationPDF(site=site_label, period=period, username=username)
    pdf.add_page()

    # ── cover band ─────────────────────────────────────────────────────────
    pdf.set_fill_color(*_NAVY)
    pdf.rect(0, 0, pdf.w, 26, style="F")
    pdf.set_xy(12, 6)
    pdf.set_font("helvetica", "B", 15)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 8, _latin("Site-Wide Valuation and 30-Day Burn Value"))
    pdf.set_xy(12, 15)
    pdf.set_font("helvetica", "", 8.5)
    pdf.cell(0, 5, _latin(f"{site_label}   |   {period}   |   "
                          f"generated {d['generated_at']}"))
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(32)

    # ── KPI row ────────────────────────────────────────────────────────────
    y = pdf.get_y()
    inner = pdf.w - 24
    bw = (inner - 3 * 4) / 4
    _kpi_box(pdf, 12, y, bw, 20, "Stock value (priced lines)",
             _money(stock["total_value"], cur),
             f"{stock['valued_items']} priced of "
             f"{stock['valued_items'] + stock['unvalued_items']} lines")
    # ⚠️ THE UN-COSTED BOX SITS BESIDE THE VALUE, NOT IN A FOOTNOTE ONLY. A
    # reader who sees only the first box has been told a number without its
    # denominator, and that is the failure this whole report guards against.
    _kpi_box(pdf, 12 + bw + 4, y, bw, 20, "Not valued",
             f"{stock['unvalued_items']} items",
             f"{stock['unvalued_qty']:,.0f} units with no unit cost",
             sub_color=_RED if stock["unvalued_items"] else _MUTED)
    _kpi_box(pdf, 12 + 2 * (bw + 4), y, bw, 20,
             f"{burn['days']}-day burn value", _money(burn["total_value"], cur),
             f"{_money(burn['daily_value'], cur)} per day")
    _kpi_box(pdf, 12 + 3 * (bw + 4), y, bw, 20, "Months of cover",
             (f"{d['months_cover']:.1f}" if d.get("months_cover") is not None
              else "n/a"),
             ("at the current burn rate" if d.get("months_cover") is not None
              else "no consumption in the window"))
    pdf.set_y(y + 26)

    # ── stock by site ──────────────────────────────────────────────────────
    rows = [[s["site"], _fmt(s["valued_items"]), _money(s["value"], cur),
             _fmt(s["unvalued_items"]), f"{s['unvalued_qty']:,.0f}"]
            for s in stock["sites"]]
    if rows:
        rows.append(["TOTAL", _fmt(stock["valued_items"]),
                     _money(stock["total_value"], cur),
                     _fmt(stock["unvalued_items"]),
                     f"{stock['unvalued_qty']:,.0f}"])
    _table(pdf, "Stock valuation by site",
           ["Site", "Priced lines", f"Value ({cur})", "Not valued",
            "Not-valued qty"],
           rows or [["(no stock on hand)", "", "", "", ""]],
           sub=(f"Priced coverage {stock['coverage_pct']}% of lines. "
                "Not-valued lines are EXCLUDED from the value column."))
    _footnote(pdf, stock["unvalued_items"], cur)

    # ── burn by site ───────────────────────────────────────────────────────
    brows = [[s["site"], f"{s['qty']:,.1f}", _money(s["value"], cur),
              _money(s["value"] / burn["days"], cur), _fmt(s["unvalued_items"])]
             for s in burn["sites"]]
    _table(pdf, f"Consumption value — rolling {burn['days']} days",
           ["Site", "Qty consumed", f"Value ({cur})", f"Per day ({cur})",
            "Not valued"],
           brows or [["(nothing consumed in the window)", "", "", "", ""]],
           sub=(f"From {burn['since']}. The per-day figure divides by the FULL "
                f"{burn['days']}-day window, not by the days that had activity."))
    _footnote(pdf, burn["unvalued_items"], cur)

    # ── top consumers ──────────────────────────────────────────────────────
    if burn["top_lines"]:
        _table(pdf, "Highest-value consumption in the window",
               ["Site", "SAP", "Material", "Qty", f"Unit ({cur})",
                f"Value ({cur})"],
               [[r["site"], r["sap"], r["name"] or "-", f"{r['qty']:,.1f}",
                 f"{r['unit_cost']:,.2f}", f"{r['value']:,.2f}"]
                for r in burn["top_lines"]],
               sub="Priced lines only, highest value first.")

    # ── the SME block, deliberately apart ──────────────────────────────────
    if sme.get("available"):
        _table(pdf, "Material Estimator seed (SME) — stated separately",
               ["Scope", "Seed lines", "Seed on hand", "Seed on order"],
               [["Project" if sme.get("scope") == "project" else "-",
                 _fmt(sme.get("lines")), f"{sme.get('seed_on_hand', 0):,.0f}",
                 f"{sme.get('seed_on_order', 0):,.0f}"]],
               sub=("⚠️ NOT ADDED TO THE FIGURES ABOVE. The estimator seed is a "
                    "frozen project-wide snapshot of what the estimate said "
                    "would be needed; the tables above are the live ERP ledger "
                    "of what is on the shelf today. They describe different "
                    "things about the same site, and a sum of the two would "
                    "double-count every material that appears in both."))
    return bytes(pdf.output())


def _footnote(pdf: FPDF, unvalued: int, cur: str) -> None:
    """The sentence that keeps the number above honest."""
    if not unvalued:
        return
    _ensure_room(pdf, 8)
    pdf.set_font("helvetica", "I", 6.5)
    pdf.set_text_color(*_MUTED)
    pdf.multi_cell(0, 3.4, _latin(
        f"Not Valued ({unvalued} items): these lines have no unit cost on the "
        f"inventory master, so they are counted and excluded rather than valued "
        f"at {cur} 0. The value shown therefore covers the priced portion only "
        f"and is a FLOOR, not a total."))
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1.5)
