"""
backend/api/sme_export_layouts.py — legacy SME workbook layouts (T3).

Byte-faithful port of the legacy Streamlit writers in
pages_internal/material_estimator_portal.py:
  - `_equipment_report_excel`   (lines ~2040-2406)  → equipment_report_xlsx()
  - `_location_report_excel`    (lines ~2426-2640)  → location_report_xlsx()
  - `generate_excel_report`     (lines ~1812+)      → single_table_xlsx()
  - `_standard_filename`        (lines ~105-114)    → legacy_filename()

Deliberately written with **xlsxwriter** (already a repo dependency — the
legacy portal uses it): the blueprint's format dicts, merge_range/insert_image
calls and row geometry translate 1:1, so there is no re-implementation drift.

Every sheet shares the legacy 5-row header:
  rows 0-3  logo (pages_internal/sme_logo.png) + right-aligned meta
            ("Report Generated:" timestamp · "Generated By:" username)
  row 4     merged title bar (scheme title_bg, white bold 13pt, height 22)
then the body:
  equipment report  → "1. Summary by Equipment (Total SQM)" ·
                      "2. Summary by System Code (Total SQM)" ·
                      "3. Detailed Table" (autofilter) — each with a
                      GRAND TOTAL row in the scheme's total colors
  location report   → main alloc table + GRAND TOTAL, then three summary
                      blocks (System Code · Equipment · Material)
  single table      → header row 5, data rows 6+, GRAND TOTAL last

Pure formatting helpers — no DB access, no writes (SME Canon intact).
"""
from __future__ import annotations

import io
import os
from datetime import date, datetime

# Legacy color schemes — verbatim from material_estimator_portal.py:1799.
COLOR_SCHEMES = {
    "dashboard":   {"title_bg": "#1A2A3A", "header_bg": "#2D4A6A", "total_bg": "#F0C040", "total_fg": "#000000"},
    "brown_field": {"title_bg": "#0F2D52", "header_bg": "#1E5799", "total_bg": "#BDD7F0", "total_fg": "#000000"},
    "train_j":     {"title_bg": "#4A2E00", "header_bg": "#A0620A", "total_bg": "#FDE8A0", "total_fg": "#000000"},
    "train_k":     {"title_bg": "#0A2E1A", "header_bg": "#1A6B48", "total_bg": "#B3F0D8", "total_fg": "#000000"},
    "session":     {"title_bg": "#2D1A52", "header_bg": "#5B2D8E", "total_bg": "#E5D0F0", "total_fg": "#000000"},
    "execution":   {"title_bg": "#3A0A0A", "header_bg": "#8E1A1A", "total_bg": "#F5C6C6", "total_fg": "#000000"},
    "overview":    {"title_bg": "#0A2A2A", "header_bg": "#0E7490", "total_bg": "#A5F3FC", "total_fg": "#000000"},
}
LOC_COLOR_MAP = {"Brown Field": "brown_field", "TRAIN J": "train_j", "TRAIN K": "train_k"}

# Phase B: the logo is vendored next to this module so the new stack never
# reaches into legacy/ (the original lives at legacy/pages_internal/).
_LOGO_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "sme_logo.png")

TITLE_ROW = 4  # rows 0-3 = logo + meta band


def legacy_filename(stem: str, username: str, ext: str) -> str:
    """Legacy convention: <ReportName>_<username>_<YYYY-MM-DD>.<ext>."""
    def _safe(s: str) -> str:
        return "".join(c if c.isalnum() or c in "._-" else "-" for c in str(s)).strip("-")
    base = _safe(stem) or "report"
    user = _safe(username) or "user"
    return f"{base}_{user}_{date.today().strftime('%Y-%m-%d')}.{ext.lstrip('.')}"


def loc_scheme(location: str | None) -> str:
    return LOC_COLOR_MAP.get(str(location or ""), "dashboard")


# ─── shared building blocks ──────────────────────────────────────────────────
def _formats(wb, cs: dict) -> dict:
    """The exact legacy format dicts (portal lines 2147-2160)."""
    return {
        "title": wb.add_format({"bold": True, "font_size": 13, "font_color": "#FFFFFF",
            "bg_color": cs["title_bg"], "align": "center", "valign": "vcenter", "border": 0}),
        "header": wb.add_format({"bold": True, "font_size": 10, "font_color": "#FFFFFF",
            "bg_color": cs["header_bg"], "align": "center", "valign": "vcenter", "border": 1}),
        "data": wb.add_format({"font_size": 9, "border": 1, "valign": "vcenter"}),
        "total": wb.add_format({"bold": True, "font_size": 10, "border": 1,
            "bg_color": cs["total_bg"], "font_color": cs["total_fg"], "valign": "vcenter"}),
        "subtitle": wb.add_format({"bold": True, "font_size": 11, "italic": True,
            "font_color": "#FFFFFF", "bg_color": cs["header_bg"], "align": "left",
            "valign": "vcenter", "border": 1}),
        "meta_label": wb.add_format({"font_size": 8, "bold": True, "align": "right",
            "valign": "vcenter", "font_color": "#555555"}),
        "meta_value": wb.add_format({"font_size": 8, "align": "left",
            "valign": "vcenter", "font_color": "#333333"}),
    }


def _header_block(ws, fmts: dict, title: str, n_cols: int, username: str) -> None:
    """Rows 0-3 logo + meta, row 4 merged title bar (portal lines 2162-2185)."""
    if os.path.exists(_LOGO_PATH):
        try:
            from PIL import Image as _PILImage
            buf = io.BytesIO()
            with _PILImage.open(_LOGO_PATH) as img:
                img = img.resize((121, 83), _PILImage.Resampling.LANCZOS)
                img.save(buf, format="PNG", dpi=(96, 96))
            buf.seek(0)
            ws.insert_image(0, 0, "logo.png", {"image_data": buf,
                "x_offset": 4, "y_offset": 4, "object_position": 1})
        except Exception:
            pass  # logo is decoration — never fail an export over it
    for r in range(4):
        ws.set_row(r, 16)
    if n_cols >= 2:
        gen_time = datetime.now().strftime("%Y-%m-%d  %H:%M")
        ws.write(1, n_cols - 2, "Report Generated:", fmts["meta_label"])
        ws.write(1, n_cols - 1, gen_time, fmts["meta_value"])
        ws.write(2, n_cols - 2, "Generated By:", fmts["meta_label"])
        ws.write(2, n_cols - 1, username or "Smart Material Estimator", fmts["meta_value"])
    if title and n_cols > 1:
        ws.merge_range(TITLE_ROW, 0, TITLE_ROW, n_cols - 1, title, fmts["title"])
    elif title:
        ws.write(TITLE_ROW, 0, title, fmts["title"])
    ws.set_row(TITLE_ROW, 22)


def _cell(v):
    return "" if v is None else v


def _num(v) -> float:
    try:
        return float(v or 0)
    except (TypeError, ValueError):
        return 0.0


def _code_sort_key(v) -> int:
    """Legacy numeric-first code sort (int(code) else 9999)."""
    s = str(v)
    return int(s) if s.isdigit() else 9999


def _write_block(ws, fmts, start_row: int, subtitle: str, cols: list[str],
                 rows: list[list], n_cols: int, *, total_label_col: int = 0,
                 total_col: int | None = None) -> int:
    """One legacy summary block: merged subtitle, header, data, GRAND TOTAL.
    Returns the last written row index. `total_col` defaults to the last col."""
    sub_row, hdr_row, data_r = start_row, start_row + 1, start_row + 2
    span = min(n_cols, len(cols))
    if span > 1:
        ws.merge_range(sub_row, 0, sub_row, span - 1, subtitle, fmts["subtitle"])
    else:
        ws.write(sub_row, 0, subtitle, fmts["subtitle"])
    ws.set_row(sub_row, 20)
    for ci, name in enumerate(cols):
        ws.write(hdr_row, ci, name, fmts["header"])
    ws.set_row(hdr_row, 18)
    for ri, row in enumerate(rows):
        for ci, val in enumerate(row):
            ws.write(data_r + ri, ci, _cell(val), fmts["data"])
    if not rows:
        return hdr_row
    tc = total_col if total_col is not None else len(cols) - 1
    gt_row = data_r + len(rows)
    ws.write(gt_row, total_label_col, "GRAND TOTAL", fmts["total"])
    for ci in range(len(cols)):
        if ci == total_label_col:
            continue
        if ci == tc:
            ws.write(gt_row, ci, round(sum(_num(r[tc]) for r in rows), 3), fmts["total"])
        else:
            ws.write(gt_row, ci, "", fmts["total"])
    return gt_row


def _auto_widths(ws, blocks: list[tuple[list[str], list[list]]], n_cols: int,
                 pad: int = 3, cap: int = 42) -> None:
    """Legacy auto-width: max content length across every block per column."""
    for ci in range(n_cols):
        cands = []
        for cols, rows in blocks:
            if ci < len(cols):
                lens = [len(str(cols[ci]))] + [len(str(_cell(r[ci]))) for r in rows]
                cands.append(max(lens))
        ws.set_column(ci, ci, min((max(cands) if cands else 10) + pad, cap))


def _sheet_name(name: str, used: set[str]) -> str:
    clean = str(name)[:31] or "Sheet"
    for ch in "[]:*?/\\":
        clean = clean.replace(ch, "-")
    base, n = clean, 2
    while clean in used:
        suffix = f" ({n})"
        clean, n = base[:31 - len(suffix)] + suffix, n + 1
    used.add(clean)
    return clean


# ─── Equipment Report (blueprint: _equipment_report_excel) ───────────────────
# Sheet spec: {"name", "title", "color_scheme",
#              "rows": [{"Location","Type","Equipment Tag No.","Equipment Name",
#                        "System Code","System Name","Total SQM"}]}
_EQ_MAIN_COLS = ["Location", "Type", "Equipment Tag No.", "System Code",
                 "System Name", "Total SQM"]
_EQ_SUMMARY_COLS = ["Equipment Tag No.", "Equipment Name", "System Name", "Total SQM"]
_SC_SUMMARY_COLS = ["System Code", "System Name", "Total SQM"]


def _eq_summaries(rows: list[dict]) -> tuple[list[list], list[list]]:
    """(summary-by-equipment, summary-by-system-code) from detail rows —
    legacy grouping incl. the '+'-joined system names per equipment."""
    by_code: dict[tuple, float] = {}
    code_order: list[tuple] = []
    for r in rows:
        k = (str(r.get("System Code", "")), str(r.get("System Name", "")))
        if k not in by_code:
            by_code[k] = 0.0
            code_order.append(k)
        by_code[k] += _num(r.get("Total SQM"))
    code_order.sort(key=lambda k: _code_sort_key(k[0]))
    sc_rows = [[c, n, round(by_code[(c, n)], 2)] for c, n in code_order]

    by_tag: dict[str, dict] = {}
    for r in sorted(rows, key=lambda x: (str(x.get("Equipment Tag No.", "")),
                                         _code_sort_key(x.get("System Code")))):
        tag = str(r.get("Equipment Tag No.", ""))
        a = by_tag.setdefault(tag, {"name": r.get("Equipment Name", "") or "",
                                    "systems": [], "sqm": 0.0})
        sn = str(r.get("System Name", "") or "")
        if sn and sn not in a["systems"]:
            a["systems"].append(sn)
        a["sqm"] += _num(r.get("Total SQM"))
    eq_rows = [[t, a["name"], "+".join(a["systems"]), round(a["sqm"], 2)]
               for t, a in by_tag.items()]
    return eq_rows, sc_rows


def _write_equipment_sheet(wb, spec: dict, username: str, used: set[str]) -> None:
    rows = spec.get("rows", [])
    cs = COLOR_SCHEMES.get(spec.get("color_scheme", "dashboard"), COLOR_SCHEMES["dashboard"])
    fmts = _formats(wb, cs)
    ws = wb.add_worksheet(_sheet_name(spec.get("name", "Report"), used))

    main_rows = [[_cell(r.get(c)) for c in _EQ_MAIN_COLS] for r in rows]
    eq_rows, sc_rows = _eq_summaries(rows)
    n_cols = max(len(_EQ_MAIN_COLS), len(_EQ_SUMMARY_COLS), len(_SC_SUMMARY_COLS))

    _header_block(ws, fmts, spec.get("title", ""), n_cols, username)

    # SECTION 1 — Summary by Equipment (legacy order: equipment first)
    end = _write_block(ws, fmts, TITLE_ROW + 1, "1. Summary by Equipment (Total SQM)",
                       _EQ_SUMMARY_COLS, eq_rows, n_cols)
    # SECTION 2 — Summary by System Code (one blank row between blocks)
    end = _write_block(ws, fmts, end + 2, "2. Summary by System Code (Total SQM)",
                       _SC_SUMMARY_COLS, sc_rows, n_cols)
    # SECTION 3 — Detailed table (+ GRAND TOTAL row, autofilter on the header)
    det_sub, det_hdr, det_data = end + 2, end + 3, end + 4
    span = min(n_cols, len(_EQ_MAIN_COLS))
    if span > 1:
        ws.merge_range(det_sub, 0, det_sub, span - 1, "3. Detailed Table", fmts["subtitle"])
    else:
        ws.write(det_sub, 0, "3. Detailed Table", fmts["subtitle"])
    ws.set_row(det_sub, 20)
    for ci, name in enumerate(_EQ_MAIN_COLS):
        ws.write(det_hdr, ci, name, fmts["header"])
    ws.set_row(det_hdr, 18)
    ws.autofilter(det_hdr, 0, det_hdr, len(_EQ_MAIN_COLS) - 1)
    for ri, row in enumerate(main_rows):
        for ci, val in enumerate(row):
            ws.write(det_data + ri, ci, _cell(val), fmts["data"])
    if main_rows:
        gt = det_data + len(main_rows)
        sqm_i = _EQ_MAIN_COLS.index("Total SQM")
        ws.write(gt, 0, "GRAND TOTAL", fmts["total"])
        for ci in range(1, len(_EQ_MAIN_COLS)):
            ws.write(gt, ci, round(sum(_num(r[sqm_i]) for r in main_rows), 2)
                     if ci == sqm_i else "", fmts["total"])

    _auto_widths(ws, [(_EQ_MAIN_COLS, main_rows), (_SC_SUMMARY_COLS, sc_rows),
                      (_EQ_SUMMARY_COLS, eq_rows)], n_cols)


def _write_all_codes_sheet(wb, all_rows: list[dict], username: str, used: set[str]) -> None:
    """Legacy 'All System Codes' sheet — codes-only totals, overview scheme."""
    _, sc_rows = _eq_summaries(all_rows)
    cs = COLOR_SCHEMES["overview"]
    fmts = _formats(wb, cs)
    ws = wb.add_worksheet(_sheet_name("All System Codes", used))
    n_cols = len(_SC_SUMMARY_COLS)
    _header_block(ws, fmts, "Equipment Report — All System Codes (Total SQM)",
                  n_cols, username)
    hdr, data = TITLE_ROW + 1, TITLE_ROW + 2
    for ci, name in enumerate(_SC_SUMMARY_COLS):
        ws.write(hdr, ci, name, fmts["header"])
    ws.set_row(hdr, 18)
    ws.autofilter(hdr, 0, hdr, n_cols - 1)
    for ri, row in enumerate(sc_rows):
        for ci, val in enumerate(row):
            ws.write(data + ri, ci, _cell(val), fmts["data"])
    if sc_rows:
        gt = data + len(sc_rows)
        ws.write(gt, 0, "GRAND TOTAL", fmts["total"])
        ws.write(gt, 1, "", fmts["total"])
        ws.write(gt, 2, round(sum(_num(r[2]) for r in sc_rows), 2), fmts["total"])
    _auto_widths(ws, [(_SC_SUMMARY_COLS, sc_rows)], n_cols)


def equipment_report_xlsx(location_sheets: list[dict], all_eq_sheet: dict | None = None,
                          include_all_codes_sheet: bool = False,
                          username: str = "") -> bytes:
    """The legacy Equipment Report workbook (multi-sheet)."""
    import xlsxwriter
    buf = io.BytesIO()
    used: set[str] = set()
    with xlsxwriter.Workbook(buf, {"in_memory": True}) as wb:
        for spec in location_sheets:
            _write_equipment_sheet(wb, spec, username, used)
        if all_eq_sheet is not None:
            _write_equipment_sheet(wb, all_eq_sheet, username, used)
        if include_all_codes_sheet:
            pooled = (all_eq_sheet or {}).get("rows") or \
                [r for s in location_sheets for r in s.get("rows", [])]
            _write_all_codes_sheet(wb, pooled, username, used)
        if not used:  # xlsxwriter refuses a zero-sheet workbook
            wb.add_worksheet("Report")
    return buf.getvalue()


# ─── Location Report (blueprint: _location_report_excel) ─────────────────────
_LR_SUMMARY_COLS = ["System Code", "System Name", "Total SQM"]
_LR_EQ_COLS = ["Equipment No.", "System Name", "Total SQM"]
_LR_MAT_COLS = ["Material Code", "Material Name", "UOM", "Total Qty"]


def location_report_xlsx(sheets: list[dict], username: str = "") -> bytes:
    """Legacy Location Report: per sheet, the main alloc table + GRAND TOTAL
    then three summary blocks (System Code · Equipment · Material).

    Sheet spec: {"name", "title", "color_scheme", "columns": [str],
                 "rows": [dict]} where rows are alloc lines carrying at least
    Equipment_Tag_No. / Lining_System_Code / Lining_System_Short_Name /
    Total_SQM / Material_Code / Material_Name / UOM / Demand_Qty.
    """
    import xlsxwriter
    buf = io.BytesIO()
    used: set[str] = set()
    with xlsxwriter.Workbook(buf, {"in_memory": True}) as wb:
        for spec in sheets:
            rows: list[dict] = spec.get("rows", [])
            columns: list[str] = spec.get("columns") or (list(rows[0].keys()) if rows else [])
            cs = COLOR_SCHEMES.get(spec.get("color_scheme", "dashboard"),
                                   COLOR_SCHEMES["dashboard"])
            fmts = _formats(wb, cs)
            ws = wb.add_worksheet(_sheet_name(spec.get("name", "Report"), used))
            n_cols = len(columns)

            _header_block(ws, fmts, spec.get("title", ""), n_cols, username)

            # Main alloc table (header row 5, data 6+, GRAND TOTAL sums numerics)
            hdr, data = TITLE_ROW + 1, TITLE_ROW + 2
            for ci, name in enumerate(columns):
                ws.write(hdr, ci, name, fmts["header"])
            ws.set_row(hdr, 18)
            ws.autofilter(hdr, 0, hdr, max(n_cols - 1, 0))
            main_rows = [[_cell(r.get(c)) for c in columns] for r in rows]
            for ri, row in enumerate(main_rows):
                for ci, val in enumerate(row):
                    ws.write(data + ri, ci, _cell(val), fmts["data"])
            cur = data + len(main_rows)
            if main_rows:
                num_cols = {ci for ci in range(n_cols)
                            if any(isinstance(r[ci], (int, float)) and not isinstance(r[ci], bool)
                                   for r in main_rows)}
                ws.write(cur, 0, "GRAND TOTAL", fmts["total"])
                for ci in range(1, n_cols):
                    if ci in num_cols:
                        ws.write(cur, ci, round(sum(_num(r[ci]) for r in main_rows
                                                    if isinstance(r[ci], (int, float))), 3),
                                 fmts["total"])
                    else:
                        ws.write(cur, ci, "", fmts["total"])
                cur += 1

            # Summaries — unique (tag, code) SQM to avoid material-row double counts.
            seen: set[tuple] = set()
            tag_code: list[dict] = []
            for r in rows:
                k = (str(r.get("Equipment_Tag_No.", r.get("Equipment_Tag_No", ""))),
                     str(r.get("Lining_System_Code", "")))
                if k not in seen:
                    seen.add(k)
                    tag_code.append(r)
            by_code: dict[tuple, float] = {}
            for r in tag_code:
                k = (str(r.get("Lining_System_Code", "")),
                     str(r.get("Lining_System_Short_Name", "") or ""))
                by_code[k] = by_code.get(k, 0.0) + _num(r.get("Total_SQM"))
            sys_rows = [[c, n, round(v, 2)] for (c, n), v in
                        sorted(by_code.items(), key=lambda kv: _code_sort_key(kv[0][0]))]
            by_tag: dict[str, dict] = {}
            for r in sorted(tag_code, key=lambda x: (
                    str(x.get("Equipment_Tag_No.", x.get("Equipment_Tag_No", ""))),
                    _code_sort_key(x.get("Lining_System_Code")))):
                t = str(r.get("Equipment_Tag_No.", r.get("Equipment_Tag_No", "")))
                a = by_tag.setdefault(t, {"systems": [], "sqm": 0.0})
                sn = str(r.get("Lining_System_Short_Name", "") or "")
                if sn and sn not in a["systems"]:
                    a["systems"].append(sn)
                a["sqm"] += _num(r.get("Total_SQM"))
            eq_rows = [[t, "+".join(a["systems"]), round(a["sqm"], 2)]
                       for t, a in by_tag.items()]
            by_mat: dict[tuple, float] = {}
            mat_order: list[tuple] = []
            for r in rows:
                k = (str(r.get("Material_Code", "")), str(r.get("Material_Name", "") or ""),
                     str(r.get("UOM", "") or ""))
                if k not in by_mat:
                    by_mat[k] = 0.0
                    mat_order.append(k)
                by_mat[k] += _num(r.get("Demand_Qty"))
            mat_rows = [[c, n, u, round(by_mat[(c, n, u)], 3)]
                        for c, n, u in sorted(mat_order)]

            cur = _write_block(ws, fmts, cur, "Summary by System Code (Total SQM)",
                               _LR_SUMMARY_COLS, sys_rows, n_cols)
            cur = _write_block(ws, fmts, cur + 1, "Summary by Equipment (Total SQM)",
                               _LR_EQ_COLS, eq_rows, n_cols)
            _write_block(ws, fmts, cur + 1, "Summary by Material (Total Qty)",
                         _LR_MAT_COLS, mat_rows, n_cols)

            _auto_widths(ws, [(columns, main_rows), (_LR_SUMMARY_COLS, sys_rows),
                              (_LR_EQ_COLS, eq_rows), (_LR_MAT_COLS, mat_rows)], n_cols)
        if not used:
            wb.add_worksheet("Report")
    return buf.getvalue()


# ─── Single-table sheets (blueprint: generate_excel_report) ──────────────────
def single_table_xlsx(sheets: list[dict], username: str = "") -> bytes:
    """Legacy single-table layout per sheet: 5-row header + header row + data
    + GRAND TOTAL (numeric columns summed). Used for the System Code Report
    (Summary sheet + one sheet per code).

    Sheet spec: {"name", "title", "color_scheme", "columns": [str], "rows": [dict]}
    """
    import xlsxwriter
    buf = io.BytesIO()
    used: set[str] = set()
    with xlsxwriter.Workbook(buf, {"in_memory": True}) as wb:
        for spec in sheets:
            rows: list[dict] = spec.get("rows", [])
            columns: list[str] = spec.get("columns") or (list(rows[0].keys()) if rows else [])
            cs = COLOR_SCHEMES.get(spec.get("color_scheme", "dashboard"),
                                   COLOR_SCHEMES["dashboard"])
            fmts = _formats(wb, cs)
            ws = wb.add_worksheet(_sheet_name(spec.get("name", "Report"), used))
            n_cols = len(columns)
            _header_block(ws, fmts, spec.get("title", ""), n_cols, username)
            hdr, data = TITLE_ROW + 1, TITLE_ROW + 2
            for ci, name in enumerate(columns):
                ws.write(hdr, ci, name, fmts["header"])
            ws.set_row(hdr, 18)
            ws.autofilter(hdr, 0, hdr, max(n_cols - 1, 0))
            main_rows = [[_cell(r.get(c)) for c in columns] for r in rows]
            for ri, row in enumerate(main_rows):
                for ci, val in enumerate(row):
                    ws.write(data + ri, ci, _cell(val), fmts["data"])
            if main_rows:
                gt = data + len(main_rows)
                num_cols = {ci for ci in range(n_cols)
                            if any(isinstance(r[ci], (int, float)) and not isinstance(r[ci], bool)
                                   for r in main_rows)}
                ws.write(gt, 0, "GRAND TOTAL", fmts["total"])
                for ci in range(1, n_cols):
                    if ci in num_cols:
                        ws.write(gt, ci, round(sum(_num(r[ci]) for r in main_rows
                                                   if isinstance(r[ci], (int, float))), 3),
                                 fmts["total"])
                    else:
                        ws.write(gt, ci, "", fmts["total"])
            _auto_widths(ws, [(columns, main_rows)], n_cols)
        if not used:
            wb.add_worksheet("Report")
    return buf.getvalue()
