from fpdf import FPDF
import pandas as pd
import datetime
import io
from io import BytesIO

try:
    import qrcode
    _HAS_QRCODE = True
except ImportError:
    _HAS_QRCODE = False

class GI_PDF(FPDF):
    """Custom PDF template with General Industries branding."""
    def header(self):
        # Branding Header
        self.set_font("helvetica", "B", 16)
        self.set_text_color(10, 25, 47) # Brand Navy
        self.cell(0, 10, "GENERAL INDUSTRIES HUB", new_x="LMARGIN", new_y="NEXT", align="C")
        
        self.set_font("helvetica", "I", 10)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, "Official System Record", new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(5)

    def footer(self):
        # Page numbers at the bottom
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} / {{nb}}", align="C")

def generate_pr_pdf(pr_number: str, site_id: str, pr_df: pd.DataFrame, generated_by: str) -> bytes:
    """
    Generates an official PDF record for a Purchase Request, 
    including immutable metadata (Who and When).
    """
    pdf = GI_PDF(orientation="P", unit="mm", format="A4")
    pdf.add_page()
    
    # --- METADATA SECTION ---
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Purchase Request (PR): {pr_number}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(50, 6, "Destination Site:", border=0)
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 6, site_id, border=0, new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(50, 6, "Generated By (User ID):", border=0)
    pdf.cell(0, 6, generated_by, border=0, new_x="LMARGIN", new_y="NEXT")
    
    pdf.cell(50, 6, "Generated On (UTC):", border=0)
    pdf.cell(0, 6, datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"), border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # --- TABLE HEADER ---
    pdf.set_font("helvetica", "B", 10)
    pdf.set_fill_color(10, 25, 47)  # Navy header
    pdf.set_text_color(255, 255, 255)

    # Column widths — Req / Recv / Pending share the right-hand strip so
    # every PR PDF shows the full fulfillment picture, not just the ask.
    col_widths = [30, 75, 20, 20, 20, 25]
    headers = ["Material Code", "Description", "Req. Qty",
               "Received", "Pending", "Status"]
    for i, h in enumerate(headers):
        is_last = (i == len(headers) - 1)
        pdf.cell(
            col_widths[i], 8, h, border=1,
            align="C" if i >= 2 else "L", fill=True,
            new_x="LMARGIN" if is_last else "RIGHT",
            new_y="NEXT" if is_last else "TOP",
        )

    # --- TABLE ROWS ---
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(0, 0, 0)

    for _, row in pr_df.iterrows():
        mat_code = str(row.get("Material_Code", "N/A"))
        desc = str(row.get("Material_Name", "Unknown Material"))[:38]
        req = float(row.get("Requested_Qty", 0) or 0)
        pend = float(row.get("Pending_Qty", 0) or 0)
        # Pending_Qty is pre-computed in the HOD query (Req - Received),
        # so we derive received from it. This keeps the PDF in lock-step
        # with the on-screen table the HOD just confirmed visually.
        recv = max(req - pend, 0)
        pend_disp = max(pend, 0)
        status = str(row.get("status", "unknown")).upper()

        pdf.cell(col_widths[0], 8, mat_code, border=1)
        pdf.cell(col_widths[1], 8, desc, border=1)
        pdf.cell(col_widths[2], 8, f"{req:g}", border=1, align="C")
        pdf.cell(col_widths[3], 8, f"{recv:g}", border=1, align="C")
        pdf.cell(col_widths[4], 8, f"{pend_disp:g}", border=1, align="C")
        pdf.cell(col_widths[5], 8, status, border=1, align="C",
                 new_x="LMARGIN", new_y="NEXT")

    # --- AUDIT FOOTNOTE ---
    pdf.ln(15)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5, "This is an automatically generated system record from the General Industries Hub. "
                         "The quantities and statuses reflected here are accurate as of the generation timestamp.")
    
    # Return raw PDF bytes so Streamlit can download it
    return bytes(pdf.output())


def generate_universal_pdf(report_title: str, df: pd.DataFrame, username: str) -> bytes:
    """
    Takes any Pandas DataFrame and converts it into a formatted Landscape PDF.
    """
    # Use your existing GI_PDF class, set to Landscape (L) to fit wide tables
    pdf = GI_PDF(orientation="L", unit="mm", format="A4")
    pdf.add_page()
    
    # 1. Report Metadata
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, report_title.upper(), new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 6, f"Generated By: {username}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Timestamp: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # Abort if table is empty
    if df.empty:
        pdf.cell(0, 10, "No data available for this report.", new_x="LMARGIN", new_y="NEXT")
        return bytes(pdf.output())

    # 2. Dynamic Column Sizing
    page_width = pdf.epw
    col_width = page_width / len(df.columns)
    row_height = 8
    
    # 3. Render Table Headers (Navy background, White text)
    pdf.set_font("helvetica", "B", 9)
    pdf.set_fill_color(10, 25, 47) 
    pdf.set_text_color(255, 255, 255)
    
    for col_name in df.columns:
        # Truncate header text if it's too long to fit
        safe_name = str(col_name)[:18]
        pdf.cell(col_width, row_height, safe_name, border=1, fill=True, align="C")
    
    # Move to the next line after headers
    pdf.ln(row_height)
    
    # 4. Render Table Data
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(0, 0, 0)
    
    for _, row in df.iterrows():
        # Prevent row data from splitting awkwardly across a page break
        if pdf.get_y() > 180: 
            pdf.add_page()
            
        for item in row:
            # Truncate cell text so it doesn't bleed into the next column
            safe_val = str(item).encode('latin-1', 'ignore').decode('latin-1')[:25] if pd.notna(item) else ""
            pdf.cell(col_width, 6, safe_val, border=1, align="C")
            
        # Move to the next line after the row finishes
        pdf.ln(6)

    return bytes(pdf.output())


def generate_qr_labels_pdf(items: list, cols: int = 3, rows_per_page: int = 4) -> bytes:
    """
    Generates a printable PDF grid of QR code labels.

    items: list of dicts with keys "SAP_Code" and "Equipment_Description".
           Each QR encodes the SAP_Code so the in-app barcode scanner can read it.
    cols / rows_per_page: grid dimensions (default 3×4 = 12 labels per A4 page).
    Returns: PDF bytes.
    """
    if not _HAS_QRCODE:
        raise ImportError("QR label generation requires: pip install qrcode[pil]")

    # ── Layout constants (all in mm, A4 portrait) ───────────────────────────
    PAGE_W, PAGE_H = 210, 297
    MARGIN = 8
    CELL_W = (PAGE_W - 2 * MARGIN) / cols          # ≈ 64.67 mm
    CELL_H = (PAGE_H - 2 * MARGIN) / rows_per_page  # ≈ 70.25 mm
    QR_SIZE = 48
    labels_per_page = cols * rows_per_page

    # Plain FPDF — no branded header/footer so the full page is usable
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(MARGIN, MARGIN, MARGIN)
    pdf.set_auto_page_break(auto=False)

    for idx, item in enumerate(items):
        if idx % labels_per_page == 0:
            pdf.add_page()

        page_idx = idx % labels_per_page
        col_idx = page_idx % cols
        row_idx = page_idx // cols

        cell_x = MARGIN + col_idx * CELL_W
        cell_y = MARGIN + row_idx * CELL_H

        # Cell border
        pdf.set_line_width(0.3)
        pdf.set_draw_color(180, 180, 180)
        pdf.rect(cell_x, cell_y, CELL_W, CELL_H)

        # QR code: generate as in-memory PNG, centered horizontally in the cell
        sap_code = str(item.get("SAP_Code", ""))
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_M,
            box_size=8,
            border=2,
        )
        qr.add_data(sap_code)
        qr.make(fit=True)
        qr_img = qr.make_image(fill_color="black", back_color="white")
        buf = BytesIO()
        qr_img.save(buf, format="PNG")
        buf.seek(0)

        qr_x = cell_x + (CELL_W - QR_SIZE) / 2
        qr_y = cell_y + 4
        pdf.image(buf, x=qr_x, y=qr_y, w=QR_SIZE, h=QR_SIZE)

        # SAP Code — bold, centered
        pdf.set_font("helvetica", "B", 8)
        pdf.set_text_color(10, 25, 47)
        pdf.set_xy(cell_x + 1, cell_y + 4 + QR_SIZE + 2)
        pdf.cell(CELL_W - 2, 5, txt=sap_code, align="C")

        # Equipment Description — smaller, truncated, centered
        desc = str(item.get("Equipment_Description", "") or "")[:35]
        pdf.set_font("helvetica", "", 6)
        pdf.set_text_color(80, 80, 80)
        pdf.set_xy(cell_x + 1, cell_y + 4 + QR_SIZE + 8)
        pdf.cell(CELL_W - 2, 4, txt=desc, align="C")

    return bytes(pdf.output())


# ===========================================================================
# REPORTS PAGE — generic tabular PDF generator
# ---------------------------------------------------------------------------
# Used for the 8 Reports-page report types so we don't repeat plumbing.
# Each row in `df` becomes a table row; the title + metadata block at the
# top includes site / date-range / username so the file stands on its own
# without the surrounding UI.
# ===========================================================================
def _latin1_safe(s) -> str:
    """
    fpdf2 + core Helvetica is latin-1 only. Map the common Unicode glyphs
    that show up in our UI strings (em-dash, arrows, smart quotes, the
    SAR currency sign, emoji) down to plain ASCII so cells never crash
    the PDF builder.
    """
    if s is None:
        return ""
    out = str(s)
    repl = {
        "—": "-", "–": "-", "→": "->", "←": "<-",
        "↑": "^", "↓": "v", "·": "*",
        "“": '"', "”": '"', "‘": "'", "’": "'",
        "✅": "[OK]", "❌": "[X]", "⚠️": "[!]",
        "🔴": "[CRIT]", "🟡": "[LOW]", "🟢": "[OK]",
        "📋": "", "📊": "", "📁": "", "📅": "", "📈": "",
        "🏷️": "", "📜": "", "📦": "", "🔥": "", "🤖": "",
        "🌐": "", "🛡️": "", "🏛️": "", "💬": "",
        "⏳": "", "🛒": "", "💡": "", "🐛": "",
    }
    for k, v in repl.items():
        out = out.replace(k, v)
    # Final pass: strip anything still outside latin-1 so fpdf can't trip.
    return out.encode("latin-1", "ignore").decode("latin-1")


def generate_report_pdf(
    *,
    title: str,
    df: pd.DataFrame,
    generated_by: str,
    site_label: str = "All Sites",
    date_from: str = "",
    date_to: str = "",
    subtitle: str = "",
    summary: dict | None = None,
) -> bytes:
    """
    Generic tabular report PDF (landscape A4). Columns auto-size from the
    dataframe's columns; cell text is truncated to keep the layout stable.
    `summary` (optional) renders a small KPI strip above the table.
    """
    pdf = GI_PDF(orientation="L", unit="mm", format="A4")
    pdf.add_page()
    title = _latin1_safe(title)
    subtitle = _latin1_safe(subtitle)
    site_label = _latin1_safe(site_label)
    generated_by = _latin1_safe(generated_by)
    date_from = _latin1_safe(date_from)
    date_to = _latin1_safe(date_to)

    # Title block
    pdf.set_font("helvetica", "B", 13)
    pdf.set_text_color(10, 25, 47)
    pdf.cell(0, 9, title, new_x="LMARGIN", new_y="NEXT")

    if subtitle:
        pdf.set_font("helvetica", "I", 10)
        pdf.set_text_color(110, 110, 110)
        pdf.cell(0, 6, subtitle, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(70, 70, 70)
    meta_bits = [
        f"Site: {site_label}",
        f"Generated by: {generated_by}",
        f"Generated at (UTC): {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}",
    ]
    if date_from or date_to:
        meta_bits.insert(0, f"Period: {date_from or '-'} -> {date_to or '-'}")
    for bit in meta_bits:
        pdf.cell(0, 5, _latin1_safe(bit), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Optional KPI strip
    if summary:
        col_w = max(60, (pdf.epw - 4) / max(len(summary), 1))
        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(212, 175, 55)
        for k in summary:
            label = _latin1_safe(str(k).replace("_", " ").title())[:24]
            pdf.cell(col_w, 6, label, border=0, align="L")
        pdf.ln(5)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(20, 20, 20)
        for v in summary.values():
            pdf.cell(col_w, 6, _latin1_safe(str(v))[:24], border=0, align="L")
        pdf.ln(8)

    if df is None or df.empty:
        pdf.set_font("helvetica", "I", 10)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "No data in the requested window.",
                 new_x="LMARGIN", new_y="NEXT")
        return bytes(pdf.output())

    # Column widths — short / numeric columns get a fixed slim width;
    # the remaining width is spread across descriptive columns. This stops
    # wide reports (Receipts: 12 columns) from collapsing into illegible
    # 22mm slivers, and lets text columns (Material, Supplier, Remarks)
    # actually breathe.
    page_w = pdf.epw
    NARROW_NAMES = {  # header → slim fixed width (mm)
        "date":            18,
        "expiry_date":     18,
        "uom":             12,
        "qty":             16,
        "quantity":        16,
        "received_qty":    18,
        "consumed_qty":    18,
        "remaining_qty":   18,
        "unit_cost":       18,
        "site":            16,
        "site_id":         16,
        "status":          18,
        "sap_code":        22,
        "sap":             22,
        "lot_number":      30,
        "pr_number":       22,
        "pr no.":          22,
        "pr":              22,
    }
    RIGHT_ALIGN_NAMES = {  # numeric columns → align right
        "qty", "quantity", "received_qty", "consumed_qty", "remaining_qty",
        "unit_cost", "receipt_value_sar", "stock_value", "total_qty",
        "issued_value_sar", "received_value_sar", "closing_value_sar",
        "opening", "issued", "received", "closing",
    }
    fixed_widths: dict[str, float] = {}
    flex_cols: list[str] = []
    for col_name in df.columns:
        key = str(col_name).strip().lower()
        if key in NARROW_NAMES:
            fixed_widths[col_name] = NARROW_NAMES[key]
        else:
            flex_cols.append(col_name)
    fixed_total = sum(fixed_widths.values())
    flex_total = max(page_w - fixed_total, 0)
    flex_w = flex_total / max(len(flex_cols), 1) if flex_cols else 0
    col_widths = {c: (fixed_widths.get(c) or flex_w) for c in df.columns}
    align_map = {
        c: ("R" if str(c).strip().lower() in RIGHT_ALIGN_NAMES else "L")
        for c in df.columns
    }
    row_h = 7

    def _draw_header():
        pdf.set_font("helvetica", "B", 8.5)
        pdf.set_fill_color(10, 25, 47)
        pdf.set_text_color(255, 255, 255)
        for col_name in df.columns:
            pdf.cell(col_widths[col_name], row_h,
                     _latin1_safe(str(col_name))[:24],
                     border=1, fill=True, align="C")
        pdf.ln(row_h)
        pdf.set_font("helvetica", "", 8)
        pdf.set_text_color(20, 20, 20)

    _draw_header()

    # Body
    for _, row in df.iterrows():
        if pdf.get_y() > 185:
            pdf.add_page()
            _draw_header()
        for col_name in df.columns:
            val = row[col_name]
            # Char budget proportional to width — looser for wide cols,
            # tighter for the narrow ones so they never wrap into garbage.
            char_budget = max(6, int(col_widths[col_name] / 1.7))
            pdf.cell(col_widths[col_name], row_h - 0.5,
                     _latin1_safe(val)[:char_budget],
                     border=1, align=align_map[col_name])
        pdf.ln(row_h - 0.5)

    return bytes(pdf.output())


# ===========================================================================
# REPORTS PAGE — Excel + CSV wrappers
# ===========================================================================
def generate_report_excel(
    *,
    title: str,
    df: pd.DataFrame,
    summary: dict | None = None,
    sheet_name: str = "Report",
) -> bytes:
    """
    Single-sheet .xlsx using openpyxl. The summary dict (if any) becomes a
    KPI block at the top of the sheet; the dataframe rows are written below
    a one-row header. We keep this dependency-light so the existing mailer
    Excel builders aren't disturbed.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment

    wb = Workbook()
    ws = wb.active
    ws.title = (sheet_name[:31] if sheet_name else "Report")

    title_font  = Font(bold=True, size=14, color="0A192F")
    label_font  = Font(bold=True, color="9A7000")
    hdr_font    = Font(bold=True, color="FFFFFF")
    hdr_fill    = PatternFill("solid", fgColor="0A192F")
    centre      = Alignment(horizontal="center", vertical="center", wrap_text=True)

    ws["A1"] = title
    ws["A1"].font = title_font
    row_idx = 3
    if summary:
        for k in summary:
            ws.cell(row=row_idx, column=1, value=str(k).replace("_", " ").title()).font = label_font
        for j, v in enumerate(summary.values(), start=1):
            ws.cell(row=row_idx + 1, column=j, value=str(v))
        row_idx += 3

    if df is not None and not df.empty:
        for j, col in enumerate(df.columns, start=1):
            cell = ws.cell(row=row_idx, column=j, value=str(col))
            cell.font = hdr_font
            cell.fill = hdr_fill
            cell.alignment = centre
        for i, (_, r) in enumerate(df.iterrows(), start=1):
            for j, v in enumerate(r.values, start=1):
                ws.cell(
                    row=row_idx + i,
                    column=j,
                    value=("" if pd.isna(v) else v),
                )
        # column widths — sensible-ish defaults
        for j, col in enumerate(df.columns, start=1):
            ws.column_dimensions[ws.cell(row=row_idx, column=j).column_letter].width = max(
                12, min(40, len(str(col)) + 6),
            )

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_report_csv(df: pd.DataFrame) -> bytes:
    """CSV bytes — useful for the format chooser's third option."""
    if df is None:
        df = pd.DataFrame()
    return df.to_csv(index=False).encode("utf-8")