from fpdf import FPDF
import pandas as pd
import datetime
import io

class GI_PDF(FPDF):
    """Custom PDF template with General Industries branding."""
    def header(self):
        # Branding Header
        self.set_font("helvetica", "B", 16)
        self.set_text_color(10, 25, 47) # Brand Navy
        self.cell(0, 10, "GENERAL INDUSTRIES HUB", new_x="LMARGIN", new_y="NEXT", align="C")
        
        self.set_font("helvetica", "I", 10)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, "Official System Record", new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(5)

    def footer(self):
        # Page numbers at the bottom
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} / {{nb}}", align="C")

def generate_pr_pdf(pr_number: str, site_id: str, pr_df: pd.DataFrame, generated_by: str) -> bytes:
    """
    Generates an official PDF record for a Purchase Request, 
    including immutable metadata (Who and When).
    """
    pdf = GI_PDF(orientation="P", unit="mm", format="A4")
    pdf.add_page()
    
    # --- METADATA SECTION ---
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Purchase Request (PR): {pr_number}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(50, 6, "Destination Site:", border=0)
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 6, site_id, border=0, new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(50, 6, "Generated By (User ID):", border=0)
    pdf.cell(0, 6, generated_by, border=0, new_x="LMARGIN", new_y="NEXT")
    
    pdf.cell(50, 6, "Generated On (UTC):", border=0)
    pdf.cell(0, 6, datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"), border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # --- TABLE HEADER ---
    pdf.set_font("helvetica", "B", 10)
    pdf.set_fill_color(10, 25, 47) # Navy header
    pdf.set_text_color(255, 255, 255)
    
    # Column widths
    col_widths = [35, 95, 30, 30]
    
    pdf.cell(col_widths[0], 8, "Material Code", border=1, fill=True)
    pdf.cell(col_widths[1], 8, "Description", border=1, fill=True)
    pdf.cell(col_widths[2], 8, "Req. Qty", border=1, align="C", fill=True)
    pdf.cell(col_widths[3], 8, "Status", border=1, align="C", fill=True, new_x="LMARGIN", new_y="NEXT")

    # --- TABLE ROWS ---
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(0, 0, 0)
    
    for _, row in pr_df.iterrows():
        # Handle long text wrapping for the description
        mat_code = str(row.get("Material_Code", "N/A"))
        desc = str(row.get("Material_Name", "Unknown Material"))[:45] # Truncate to fit
        req_qty = str(row.get("Requested_Qty", "0"))
        status = str(row.get("status", "unknown")).upper()
        
        pdf.cell(col_widths[0], 8, mat_code, border=1)
        pdf.cell(col_widths[1], 8, desc, border=1)
        pdf.cell(col_widths[2], 8, req_qty, border=1, align="C")
        pdf.cell(col_widths[3], 8, status, border=1, align="C", new_x="LMARGIN", new_y="NEXT")

    # --- AUDIT FOOTNOTE ---
    pdf.ln(15)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5, "This is an automatically generated system record from the General Industries Hub. "
                         "The quantities and statuses reflected here are accurate as of the generation timestamp.")
    
    # Return raw PDF bytes so Streamlit can download it
    return bytes(pdf.output())