/**
 * Phase 21f — the self-driving demos (flows 1 and 2, ruling Q21-14: the
 * Finance story first), and Phase 23f's twelve (ruling Q23-14). Each one is ALSO an E2E spec in the Practice leg
 * (tests/e2e/specs/demo.spec.ts), so a demo that would stall in front of
 * management fails a pull request first.
 *
 * Kept in step with `backend/api/practice_demo.CATALOG` (ids, titles, roles),
 * which the assistant reads to offer a demo — suite 21F checks they agree.
 *
 * ⚠️ Every entry a demo makes carries `DEMO-` (the remark, or the DEMO- tank),
 * so Reset demo data (HOD / Admin) removes exactly what demos made (Q21-17).
 * No supplier prices and no real site names in a sentence (Q20-17).
 * Phase 23f: a demo that changes something WITHOUT a DEMO- tag undoes it
 * itself (Link → Undo, Use this → Remove) and stops short of a numbered form;
 * Reset demo data covers the rest (practice_demo._RESET_PHASE23).
 */
import { tid } from './types'
import type { DemoScript } from './types'

const stamp = () => {
  const d = new Date()
  const p = (n: number) => String(n).padStart(2, '0')
  return `DEMO-${p(d.getDate())}${p(d.getMonth() + 1)}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`
}

export const DEMO_TANK = 'DEMO-TANK-1'

const p2 = (n: number) => String(n).padStart(2, '0')
const iso = (d: Date) => `${d.getFullYear()}-${p2(d.getMonth() + 1)}-${p2(d.getDate())}`
const ddmmyy = (d: Date) => `${p2(d.getDate())}/${p2(d.getMonth() + 1)}/${p2(d.getFullYear() % 100)}`
/** A paper date with the MONTH misread: the day is right, the month is six
 *  months off — the 01/07/26-for-01/10/26 case the real photos produced. */
/** A paper `n` days old — the overlay's Night paper is two days old (22e). */
const daysAgo = (n: number) => ddmmyy(new Date(Date.now() - n * 86_400_000))
const misreadToday = () => {
  const d = new Date()
  return `${p2(d.getDate())}/${p2(((d.getMonth() + 6) % 12) + 1)}/${p2(d.getFullYear() % 100)}`
}

export const SCRIPTS: DemoScript[] = [
  {
    id: 'consumption-to-approval',
    title: 'Issue stock, then the HOD approves it',
    blurb: 'The store keeper records an issue with its paper; the HOD approves it into the ledger.',
    roles: ['store_keeper', 'hod', 'admin'],
    vars: () => ({ ref: stamp() }),
    beats: [
      { say: 'This demo runs on Practice data. Nothing here touches the live warehouse.' },
      { say: 'We start as the store keeper, at the warehouse counter.', do: 'switch', value: 'store_keeper' },
      { say: 'This is Issue Stock. Everything that leaves the store is written here first.',
        do: 'navigate', value: '/entry/issue', until: '#SAP_Code' },
      { say: 'First the material. The store keeper finds it by name, not by code.',
        do: 'select', target: '#SAP_Code', value: 'Masking Tape', as: 'item' },
      { say: 'The line under it shows what is in stock right now, and how many days that lasts.',
        do: 'point', target: tid('item-snapshot'), optional: true, timeout: 5000 },
      { say: 'Two of them left the store today.', do: 'type', target: '#Quantity', value: '2' },
      { say: 'The work package it is charged to.', do: 'select', target: '#wbs', value: 'WBS',
        optional: true, timeout: 3000 },
      { say: 'Who received it.', do: 'type', target: '#Issued_To', value: 'Crew A' },
      { say: 'The remark carries a DEMO tag, so a trainer can clear this entry afterwards.',
        do: 'type', target: '#Remarks', value: '{ref} practice demo' },
      { say: 'Add to batch. A store keeper can add many lines and send them together.',
        do: 'click', target: 'button', text: 'Add to batch', untilText: 'Batch (1 line)' },
      { say: 'Every entry carries its paper. The demo attaches a practice slip, as you would attach a photo of the note.',
        do: 'attach', target: tid('entry-docs'), value: '{ref}', untilText: '{ref}.png' },
      { say: 'Submit the batch to the HOD.', do: 'click', target: 'button', text: 'Submit batch to HOD',
        untilText: 'submitted for HOD approval' },
      { say: 'Nothing has left the ledger yet. It waits for the HOD.' },
      { say: 'Now we sign out, and sign in as the HOD.', do: 'switch', value: 'hod' },
      { say: 'The HOD opens Approvals: everything the site has submitted, by kind.',
        do: 'navigate', value: '/hod/approvals', until: '.ant-tabs-tab' },
      { say: 'Issues.', do: 'click', target: '.ant-tabs-tab', text: 'Issues' },
      { say: 'Here is the store keeper’s line, with its DEMO tag. The analysis under it compares the draw with this material’s usual use.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' } },
      { say: 'The HOD approves it.', do: 'click', within: { css: '.ant-table-row', hasText: '{ref}' },
        target: 'button', text: 'Approve' },
      { say: 'And confirms. Approval commits it to the ledger: the stock figure changes now, and the audit log records who approved it.',
        do: 'click', target: '.ant-popconfirm .ant-btn-primary', untilText: 'Approved' },
      { say: 'That is the loop: written once at the counter, checked once by the HOD, and in the stock figure the moment it is approved.' },
    ],
  },
  {
    id: 'ss-bulk',
    title: 'Surface Shield jobs: bulk submit, then bulk approve',
    blurb: 'The supervisor files a week of lining jobs in one go; the HOD approves them in one go.',
    roles: ['store_keeper', 'supervisor', 'hod', 'admin'],
    vars: () => ({ tank: DEMO_TANK }),
    beats: [
      { say: 'This demo runs on Practice data, on a demo tank kept for it.' },
      { say: 'We start as the site supervisor, who files the lining work done each day.',
        do: 'switch', value: 'supervisor' },
      { say: 'Execution. Each card is one day of Surface Shield material drawn for one tank.',
        do: 'navigate', value: '/execution', until: 'input[aria-label="Find a job"]' },
      { say: 'We look at the demo tank.', do: 'type', target: 'input[aria-label="Find a job"]', value: '{tank}' },
      { say: 'A card is ready when the store keeper’s remark gives the area. The supervisor checks it; nothing is typed twice.',
        do: 'point', within: { css: '.gi-job-card', hasText: '{tank}' } },
      { say: 'Select all ready picks every complete card.', do: 'click', target: tid('bulk-select-ready') },
      { say: 'One review of the whole batch: the days, the tanks, the total area.',
        do: 'click', target: tid('bulk-submit'), until: tid('bulk-submit-confirm') },
      { say: 'And one click sends them all to the HOD.', do: 'click', target: tid('bulk-submit-confirm'),
        untilText: 'Submitted' },
      { say: 'Now we sign out, and sign in as the HOD.', do: 'switch', value: 'hod' },
      { say: 'The HOD opens the same page.', do: 'navigate', value: '/execution', until: '.ant-tabs-tab' },
      { say: 'Awaiting the HOD: every job submitted from the site.', do: 'click', target: '.ant-tabs-tab',
        text: 'Awaiting the HOD' },
      { say: 'The HOD ticks the demo tank’s jobs.', do: 'check',
        within: { css: '.gi-job-card', hasText: '{tank}' }, target: 'input[type=checkbox]' },
      { say: 'Approve selected. The confirmation shows the total area, and names any job drawn more than ten percent off the recipe before the click.',
        do: 'click', target: tid('hod-approve-selected'), until: tid('hod-approve-confirm') },
      { say: 'Approved. Each job’s area is credited to the tank once, and the material it drew is recorded against it.',
        do: 'click', target: tid('hod-approve-confirm'), untilText: 'Approved' },
      { say: 'A week of lining, filed and approved in two clicks each — with every number still checked.' },
    ],
  },
  {
    id: 'receive-lot',
    title: 'Receive a batch with its MFD; it appears in Lots & Expiry',
    blurb: 'A lot-tracked material is received with its batch number and manufacture date; the expiry is worked out, and FEFO knows it.',
    roles: ['store_keeper', 'hod', 'admin'],
    vars: () => ({ ref: stamp(), mfd: iso(new Date(Date.now() - 20 * 86_400_000)) }),
    beats: [
      { say: 'This demo runs on Practice data: a delivery of lining primer arrives at the store.' },
      { say: 'We start as the store keeper.', do: 'switch', value: 'store_keeper' },
      { say: 'Receive Stock. Goods are recorded here, with their paper.',
        do: 'navigate', value: '/entry/receive', until: '#SAP_Code' },
      { say: 'The material: a lot-tracked primer. Lot-tracked items ask for their batch and dates.',
        do: 'select', target: '#SAP_Code', value: 'PRACTICE PU PRIMER' },
      { say: 'Four cans.', do: 'type', target: '#Quantity', value: '4' },
      { say: 'The batch number, as printed on the can. This one carries a DEMO tag.',
        do: 'type', target: '#Lot_Number', value: '{ref}' },
      { say: 'The manufacture date from the label.', do: 'type', target: '#MFD_Date', value: '{mfd}', enter: true },
      { say: 'Leave the expiry blank: it is worked out from the manufacture date and the shelf life.',
        do: 'point', target: '#Expiry_Date', untilText: 'Leave blank', optional: true },
      { say: 'The work package.', do: 'select', target: '#wbs', value: 'WBS', optional: true, timeout: 3000 },
      { say: 'Who it came from.', do: 'type', target: '#Supplier', value: 'Practice supplier' },
      { say: 'And a DEMO remark.', do: 'type', target: '#Remarks', value: '{ref} practice demo' },
      { say: 'Add to batch.', do: 'click', target: 'button', text: 'Add to batch', untilText: 'Batch (1 line)' },
      { say: 'The delivery note goes with it: the demo attaches a practice slip.',
        do: 'attach', target: tid('entry-docs'), value: '{ref}', untilText: '{ref}.png' },
      { say: 'Submit the batch to the HOD.', do: 'click', target: 'button', text: 'Submit batch to HOD',
        untilText: 'submitted for HOD approval' },
      { say: 'Now the HOD.', do: 'switch', value: 'hod' },
      { say: 'Approvals, receipts.', do: 'navigate', value: '/hod/approvals', until: '.ant-tabs-tab' },
      { say: 'Receipts.', do: 'click', target: '.ant-tabs-tab', text: 'Receipts' },
      { say: 'The delivery, with its batch number.', do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' } },
      { say: 'The HOD approves it.', do: 'click', within: { css: '.ant-table-row', hasText: '{ref}' },
        target: 'button', text: 'Approve' },
      { say: 'And confirms.', do: 'click', target: '.ant-popconfirm .ant-btn-primary', untilText: 'Approved' },
      { say: 'Lots and Expiry: every batch on site, with its expiry and what is left of it.',
        do: 'navigate', value: '/lots', until: tid('lot-table'), timeout: 30_000 },
      { say: 'We look up the new batch.', do: 'type', target: 'input[aria-label="Find a lot"]', value: '{ref}', enter: true,
        timeout: 30_000 },
      { say: 'There it is, with the expiry worked out. When primer is issued, the earliest expiry is picked first.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' }, timeout: 40_000 },
      { say: 'From the label on the can to the expiry list, with nothing typed twice.' },
    ],
  },
  {
    id: 'loan-partial',
    title: 'Lend a tool, and take part of it back',
    blurb: 'Three clamp sets go out on loan; one comes back. The loan stays open and says what is still out.',
    roles: ['store_keeper', 'hod', 'admin'],
    vars: () => ({ ref: stamp() }),
    beats: [
      { say: 'This demo runs on Practice data: tools lent to the field.' },
      { say: 'We start as the store keeper.', do: 'switch', value: 'store_keeper' },
      { say: 'Returnable Items: the loan desk.', do: 'navigate', value: '/entry/returnables',
        until: tid('return-scan-input') },
      { say: 'Lend a tool.', do: 'click', target: 'button', text: 'Loan a tool', until: '.ant-modal' },
      { say: 'Scan the tool’s sticker. The demo types the code instead of using the camera.',
        do: 'click', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' }, target: 'button', text: 'Scan tool' },
      { say: 'The code.', do: 'type', within: { css: '.ant-modal', hasText: 'Scan the tool' },
        target: 'input[placeholder="…or type the code"]', value: '{ref}', enter: true, untilText: 'Scanned: {ref}' },
      { say: 'What it is.', do: 'type', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' },
        target: 'input[placeholder="e.g. Torque wrench — or Scan tool ↑"]', value: 'Clamp set (demo)' },
      { say: 'Who takes it.', do: 'type', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' },
        target: 'input[placeholder="Employee name — or Scan badge ↑"]', value: '{ref} crew' },
      { say: 'Three of them.', do: 'type', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' },
        target: '.ant-input-number input', value: '3' },
      { say: 'Due back in three days.', do: 'click', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' },
        target: 'button', text: '+3 days' },
      { say: 'Record the loan.', do: 'click', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' },
        target: 'button', text: 'Record loan', untilText: 'Loan recorded' },
      { say: 'Later, one clamp set comes back. The desk takes a scan of the sticker.',
        do: 'type', target: tid('return-scan-input'), value: '{ref}', enter: true, until: tid('return-panel') },
      { say: 'One back, not three.', do: 'type', within: { css: tid('return-panel'), hasText: 'Clamp set' },
        target: '[data-testid^="return-qty-"]', value: '1' },
      { say: 'Confirm the return.', do: 'click', target: tid('return-confirm'), untilText: '2 still out' },
      { say: 'The loan stays open and says two are still out. Overdue loans are chased automatically.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' }, target: '[data-testid^="loan-partial-"]' },
      { say: 'Slip prints the borrower’s slip. Its QR code finds this loan in one scan.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' }, target: '[data-testid^="loan-slip-"]', optional: true },
      { say: 'Nothing lent is forgotten, and nothing returned is counted twice.' },
    ],
  },
  {
    id: 'reorder-pace',
    title: "Set the site's SQM pace, then accept a minimum",
    blurb: 'The HOD plans how fast the site lines, and the Surface Shield minimums follow; then accepts one.',
    roles: ['hod', 'admin'],
    beats: [
      { say: 'This demo runs on Practice data. Reset demo data puts the pace and the minimum back afterwards.' },
      { say: 'We start as the HOD.', do: 'switch', value: 'hod' },
      { say: 'Stock, reorder signals: what to order, and why.', do: 'navigate', value: '/stock?tab=reorder',
        until: tid('reorder-signals') },
      { say: 'This note is the site: the area still to line, and the pace the minimums are planned on.',
        do: 'point', target: '[data-testid^="pace-note-"]' },
      { say: 'The HOD sets the pace.', do: 'click', target: '[data-testid^="pace-set-"]', until: tid('pace-input') },
      { say: 'A suggestion from the site’s own approved jobs.', do: 'point', target: tid('pace-suggestion'), optional: true },
      { say: 'Six square metres a day.', do: 'type', target: tid('pace-input'), value: '6' },
      { say: 'Save. Every Surface Shield minimum is worked out again from it.', do: 'click', target: tid('pace-save'),
        untilText: 'planned pace' },
      { say: 'We look at the lining primer.', do: 'type', target: 'input[placeholder="SAP, material code or name"]',
        value: 'PRACTICE PU PRIMER', enter: true },
      { say: 'How? shows the working: area, rate, days of cover, pack size.', do: 'point', target: tid('math-trail'), optional: true },
      { say: 'Review minimums.', do: 'click', target: tid('min-review'), until: tid('min-accept') },
      { say: 'The HOD ticks the primer.', do: 'check', within: { css: '.ant-table-row', hasText: 'PRACTICE PU PRIMER' },
        target: 'input[type=checkbox]' },
      { say: 'And accepts its minimum. It is the site’s until the HOD accepts another.',
        do: 'click', target: tid('min-accept'), until: tid('min-accepted') },
      { say: 'The minimum now follows the work actually planned, and the order brings stock back to twice it.' },
    ],
  },
  {
    id: 'ocr-paste',
    title: 'A consumption paper: date check, names, stage',
    blurb: 'A handwritten paper with a misread date and a misspelt name, checked and staged for the HOD.',
    roles: ['store_keeper', 'hod', 'admin'],
    vars: () => ({ ref: stamp(), paper: misreadToday(), today: ddmmyy(new Date()) }),
    beats: [
      { say: 'This demo runs on Practice data: a consumption paper, as the reader would read it.' },
      { say: 'We start as the store keeper.', do: 'switch', value: 'store_keeper' },
      { say: 'OCR Import. A photo goes to the local AI; this demo uses the paste box, which gives the same result.',
        do: 'navigate', value: '/entry/ocr', until: 'textarea' },
      { say: 'The paper, as read: its date, and two lines.', do: 'type', target: 'textarea',
        value: 'Date: {paper}\n{ref}, Nitril glovs, Pair, 2, PV\n{ref}, Safty goggls, Nos, 1, RIL' },
      { say: 'Parse.', do: 'click', target: 'button', text: 'Parse', until: tid('ocr-date-check') },
      { say: 'The date reads {paper}: months from today. The reader misread it, so it is not taken.',
        do: 'point', target: tid('ocr-date-check') },
      { say: 'The first suggestion keeps the day and fixes the month: {today}.', do: 'click',
        target: tid('ocr-date-candidate') },
      { say: 'Nitril glovs is green: a store keeper here taught the matcher that name.',
        do: 'point', target: tid('ocr-state-auto'), optional: true },
      { say: 'Safty goggls is gold: a suggestion. Nothing gold is filled in by itself.',
        do: 'point', target: tid('ocr-suggestion'), optional: true },
      { say: 'Accept teaches it. Next time it is green.', do: 'click', target: tid('ocr-accept'), optional: true },
      { say: 'The work type is in the workbook’s spelling: PV became PU.', do: 'point', target: tid('ocr-work-type') },
      { say: 'The paper itself is the supporting document. A photographed page is attached by itself; here the demo attaches a practice slip.',
        do: 'attach', target: tid('entry-docs'), value: '{ref}', untilText: '{ref}.png' },
      { say: 'The work package.', do: 'select', target: tid('ocr-wbs'), value: 'WBS', optional: true, timeout: 3000 },
      { say: 'Stage the rows for the HOD.', do: 'click', target: tid('ocr-stage'), until: '.ant-popconfirm' },
      { say: 'Confirm.', do: 'click', target: '.ant-popconfirm .ant-btn-primary', untilText: 'staged for HOD approval' },
      { say: 'Now the HOD.', do: 'switch', value: 'hod' },
      { say: 'Approvals, issues.', do: 'navigate', value: '/hod/approvals', until: '.ant-tabs-tab' },
      { say: 'Issues.', do: 'click', target: '.ant-tabs-tab', text: 'Issues' },
      { say: 'The paper’s lines wait here like any issue, on the date the store keeper confirmed.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' } },
      { say: 'A paper read in minutes, with every doubtful field put in front of a person.' },
    ],
  },
  // ── Phase 23f (ruling Q23-14) ─────────────────────────────────────────────
  {
    id: 'drive-freshness',
    title: "Pull from Drive, and where today's numbers came from",
    blurb: 'The chip in the top bar says how fresh the workbook data is; the HOD and Admin can pull now.',
    roles: ['hod', 'logistics', 'admin'],
    beats: [
      { say: 'This demo runs on Practice data. Practice never pulls from Google Drive, so the chip here only says Practice.' },
      { say: 'We start as the HOD.', do: 'switch', value: 'hod' },
      { say: 'The cloud chip in the top bar is on every page.', do: 'navigate', value: '/',
        until: tid('drive-freshness'), timeout: 20_000 },
      { say: 'In Live it shows the time of the last successful pull from Drive.', do: 'point', target: tid('drive-freshness') },
      { say: 'Navy means the last pull worked within the last twenty-six hours. Amber means it is older, or the ERP changes wait for the Admin’s Commit. Red means a pull failed, or Google’s sign-in ended.' },
      { say: 'Hover it, and it lists each workbook: which Drive copy GI Hub holds, and when the ERP ledger was last committed.' },
      { say: 'Beside it, Pull fetches the newest workbooks, delivery notes, certificates and requests at once. The Mac also pulls on its own schedule.' },
      { say: 'Everything a pull brings shows on the ordinary pages: receipts with their delivery notes, lots with their certificates, Requests and Pending.',
        do: 'navigate', value: '/records/receipts', until: 'input[placeholder="Search SAP code / name…"]' },
      { say: 'When the chip is navy, the screens show what the workbook says now.' },
    ],
  },
  {
    id: 'dn-wd',
    title: 'A receipt and its delivery-note photo; a WD number',
    blurb: 'Open the delivery note behind a receipt; a delivery with no note gets a WD number.',
    roles: ['hod', 'admin'],
    beats: [
      { say: 'This demo runs on Practice data: two deliveries of gasket sets, three days ago.' },
      { say: 'We start as the HOD. The ledger logs are for the HOD and above.', do: 'switch', value: 'hod' },
      { say: 'Records, Receipts: every delivery the site took in.', do: 'navigate', value: '/records/receipts',
        until: 'input[placeholder="Search SAP code / name…"]' },
      { say: 'We look up the two practice deliveries.', do: 'type', target: 'input[placeholder="Search SAP code / name…"]',
        value: 'DN example', enter: true },
      { say: 'This one came with delivery note 90001.', do: 'point',
        within: { css: '.ant-table-row', hasText: '90001' }, timeout: 20_000 },
      { say: 'The paper clip opens the delivery note itself: a read-only copy of the file in Google Drive.',
        do: 'click', within: { css: '.ant-table-row', hasText: '90001' }, target: tid('dn-open'),
        until: tid('drive-docs-modal'), timeout: 20_000 },
      { say: 'This one is a drawn practice note. In Live it is the scanned paper the driver handed over.',
        do: 'point', target: tid('drive-doc-image'), optional: true, timeout: 8000 },
      { say: 'Close it.', do: 'click', target: '.ant-modal-close' },
      { say: 'The other delivery came with no delivery note. GI Hub gives it a WD number, so it can still be found, and matched when the paper turns up.',
        do: 'point', target: tid('wd-no'), timeout: 20_000 },
      { say: 'Every receipt can be traced to its paper, or says plainly that it has none.' },
    ],
  },
  {
    id: 'mtc-confirm',
    title: 'A certificate from Drive, confirmed onto its lot',
    blurb: 'The HOD proposed which lot a certificate belongs to; QC opens it and confirms.',
    roles: ['qc', 'hod', 'admin'],
    beats: [
      { say: 'This demo runs on Practice data. Reset demo data puts the certificate back in the queue afterwards.' },
      { say: 'We start as Quality Control.', do: 'switch', value: 'qc' },
      { say: 'Lots and Expiry: every batch on site, and the certificates from Drive.', do: 'navigate', value: '/lots',
        until: tid('mtc-drive'), timeout: 30_000 },
      { say: 'A certificate that names a batch GI Hub holds is filed on its lot by itself.', do: 'point', target: tid('mtc-drive') },
      { say: 'This one names no batch, only container 1. So the HOD proposed the lot it belongs to, and QC has the last word.',
        do: 'point', target: tid('mtc-proposed'), timeout: 20_000 },
      { say: 'QC opens the certificate first.', do: 'click', within: { css: tid('mtc-proposed'), hasText: 'container 1' },
        target: 'button', text: 'container 1', until: tid('drive-docs-modal') },
      { say: 'Close it.', do: 'click', target: '.ant-modal-close' },
      { say: 'Confirm. The file becomes the certificate of that lot, and the dates printed on it are read for that lot.',
        do: 'click', target: tid('mtc-confirm'), untilText: 'Certificate filed' },
      { say: 'The HOD can propose; only QC can confirm. A certificate is never filed on a guess.' },
    ],
  },
  {
    id: 'requests-sap',
    title: 'Requests & Pending: map a request to its SAP code',
    blurb: 'A request line with no SAP code is linked to its item, then the decision is undone.',
    roles: ['hod', 'logistics', 'admin'],
    beats: [
      { say: 'This demo runs on Practice data: a request workbook mailed six days ago.' },
      { say: 'We start as the HOD.', do: 'switch', value: 'hod' },
      { say: 'Requests and Pending: what the site asked for, and what has arrived.', do: 'navigate',
        value: '/requests-pending', until: tid('req-needs-sap'), timeout: 30_000 },
      { say: 'Some request lines carry no SAP code, so they count against nothing. They are listed here.',
        do: 'point', target: tid('req-needs-sap') },
      { say: 'GI Hub offers the closest items it stocks. For this trowel none is right, and a suggestion is never taken by itself.',
        do: 'point', within: { css: `${tid('req-needs-sap')} tr`, hasText: 'Garden Trowel' }, target: tid('sap-suggestion'),
        optional: true, timeout: 5000 },
      { say: 'The HOD chooses the item: a notched trowel.', do: 'select',
        within: { css: `${tid('req-needs-sap')} tr`, hasText: 'Garden Trowel' }, target: tid('sap-pick'), value: 'Notched Trowel' },
      { say: 'Link. The line now counts against that item, here and in Smart Reorder.', do: 'click',
        within: { css: `${tid('req-needs-sap')} tr`, hasText: 'Garden Trowel' }, target: tid('sap-link'), untilText: 'linked to' },
      { say: 'The workbook is never changed. GI Hub remembers the decision for this name, so next month’s request is linked by itself.' },
      { say: 'A line with a catalogue code GI Hub does not stock yet waits under Not stocked yet. No SAP number is made up; it links itself when the workbook adds the item.',
        do: 'click', target: '.ant-segmented-item', text: 'Not stocked yet' },
      { say: 'Decided lists every decision, with who made it.', do: 'click', target: '.ant-segmented-item', text: 'Decided' },
      { say: 'Undo puts a line back on the list.', do: 'click',
        within: { css: `${tid('req-needs-sap')} tr`, hasText: 'Garden Trowel' }, target: tid('sap-undo'), until: '.ant-popconfirm' },
      { say: 'Confirm.', do: 'click', target: '.ant-popconfirm .ant-btn-primary', untilText: 'Undone' },
      { say: 'Admin, HOD and Logistics decide. The store keeper sees the list, and cannot change it.' },
    ],
  },
  {
    id: 'ocr-page-tank',
    title: "A paper's tank, set once for the whole page",
    blurb: 'A Night paper already in the workbook is compared; ditto marks and a scribbled tank are filled from one choice.',
    roles: ['store_keeper', 'hod', 'admin'],
    vars: () => ({ paper: daysAgo(2) }),
    beats: [
      { say: 'This demo runs on Practice data: a Night paper from two days ago, as the reader would read it. Nothing is staged.' },
      { say: 'We start as the store keeper.', do: 'switch', value: 'store_keeper' },
      { say: 'OCR Import. The demo uses the paste box, which gives the same result as a photo.',
        do: 'navigate', value: '/entry/ocr', until: 'textarea' },
      { say: 'Three lines. The first tank is a scribble, the second a ditto mark, the third is written clearly.',
        do: 'type', target: 'textarea',
        value: 'Date: {paper} (Night)\nAria Bellweather, Bonding Adhesive, EA, 1, R/L, Tnk ?7\nAria Bellweather, Solvent Wash, EA, 2, R/L, ″\nAria Bellweather, Masking tape, Nos, 3, R/L, Tank one' },
      { say: 'Parse.', do: 'click', target: 'button', text: 'Parse', until: tid('ocr-page-tank-pick'), timeout: 30_000 },
      { say: 'Night, on the date box, makes it a Night paper, and the Night preparer of that date is filled in.',
        do: 'point', target: tid('ocr-shift-tag'), optional: true, timeout: 5000 },
      { say: 'The night preparer had already typed this paper into the workbook. So it is compared line by line, and never staged a second time.',
        do: 'point', target: tid('ocr-compare'), optional: true, timeout: 10_000 },
      { say: 'The third row matched its tank. The first two did not.', do: 'point', target: tid('ocr-tank') },
      { say: 'Tank for this whole page offers the tanks this site used in the seven days before the paper’s date.',
        do: 'point', target: tid('ocr-page-tank') },
      { say: 'The store keeper chooses one.', do: 'select', target: tid('ocr-page-tank-pick'), value: '' },
      { say: 'Rows one and two now carry it. Row three named its own tank, so it is not changed.',
        do: 'point', target: tid('ocr-page-tank-undo') },
      { say: 'Undo puts back exactly what was there.', do: 'click', target: tid('ocr-page-tank-undo') },
      { say: 'Behind the scenes, a second read looks again at any numbered line the first read skipped, and adds what it finds. Nobody waits for it.' },
    ],
  },
  {
    id: 'pr-pictures',
    title: 'Raise a PR with pictures; Logistics sees them',
    blurb: 'The HOD raises a PR for a catalogue item not stocked yet; Logistics opens it and sees the picture.',
    roles: ['hod', 'admin'],
    vars: () => ({ ref: stamp() }),
    beats: [
      { say: 'This demo runs on Practice data. The PR carries a DEMO tag, so Reset demo data removes it.' },
      { say: 'We start as the HOD.', do: 'switch', value: 'hod' },
      { say: 'Purchase requests.', do: 'navigate', value: '/hod/prs', until: '.ant-tabs-tab' },
      { say: 'Create PR.', do: 'click', target: '.ant-tabs-tab', text: 'Create PR', until: tid('pr-item') },
      { say: 'The note carries the DEMO tag.', do: 'type',
        target: 'textarea[placeholder="Applies to lines without their own note"]', value: '{ref} practice demo' },
      { say: 'The material. Typing searches the company catalogue too: this rubber sheet is not stocked here yet, and it has a picture.',
        do: 'select', target: tid('pr-item'), value: 'MAT-990001' },
      { say: 'Twenty metres.', do: 'type', target: 'input[placeholder="Qty"]', value: '20' },
      { say: 'Create the PR. The line carries its catalogue code and no SAP number; none is made up.',
        do: 'click', target: 'button', text: 'Create PR', untilText: 'created (' },
      { say: 'GI Hub numbers the PR.', do: 'read', target: '.ant-message-notice', text: 'created',
        pattern: 'PR (\\S+) created', as: 'pr' },
      { say: 'Submit to Logistics.', do: 'click', target: '.ant-tabs-tab', text: 'Submit to Logistics', until: '.ant-table-row' },
      { say: 'PR {pr}, waiting to go.', do: 'point', within: { css: '.ant-table-row', hasText: '{pr}' }, timeout: 20_000 },
      { say: 'Submit it.', do: 'click', within: { css: '.ant-table-row', hasText: '{pr}' }, target: 'button',
        text: 'Submit to Logistics', until: '.ant-popconfirm' },
      { say: 'Confirm.', do: 'click', target: '.ant-popconfirm .ant-btn-primary', untilText: 'to Logistics' },
      { say: 'Now Logistics, who will buy it.', do: 'switch', value: 'logistics' },
      { say: 'Incoming PRs.', do: 'navigate', value: '/logistics', until: '.ant-table-row', timeout: 30_000 },
      { say: 'Logistics opens PR {pr}.', do: 'click', within: { css: '.ant-table-row', hasText: '{pr}' },
        target: '.ant-table-row-expand-icon', until: tid('pr-lines-pics'), timeout: 20_000 },
      { say: 'Each line shows its picture, so the buyer sees which sheet the site means. Not stocked yet says it will link itself when the workbook adds the item.',
        do: 'point', target: tid('pr-lines-pics') },
      { say: 'A picture on the PR saves a wrong size arriving on a truck.' },
    ],
  },
  {
    id: 'catalogue-family',
    title: 'A picture for a material, and for its family',
    blurb: 'A sheet with no picture uses its sister size’s picture, then it is removed again.',
    roles: ['logistics', 'hod', 'admin'],
    beats: [
      { say: 'This demo runs on Practice data: drawn pictures, never real photos.' },
      { say: 'We start as Logistics. Admin, the HOD and Logistics look after the pictures.', do: 'switch', value: 'logistics' },
      { say: 'The catalogue: every GI code in the company list, about six thousand in Live, with their pictures.',
        do: 'navigate', value: '/catalogue', until: tid('catalogue-search'), timeout: 30_000 },
      { say: 'We look up a rubber sheet.', do: 'type', target: tid('catalogue-search'), value: 'Practice Rubber Sheet', enter: true },
      { say: 'The six millimetre sheet has no picture yet.', do: 'point',
        within: { css: '.ant-table-row', hasText: 'MAT-990002' }, timeout: 20_000 },
      { say: 'Open it.', do: 'click', within: { css: '.ant-table-row', hasText: 'MAT-990002' },
        until: tid('catalogue-editor') },
      { say: 'GI Hub found its family: the five millimetre sheet shares its name apart from the size, and has a picture. Nothing is attached until somebody chooses.',
        do: 'point', target: tid('catalogue-family'), timeout: 20_000 },
      { say: 'Use this.', do: 'click', within: { css: tid('catalogue-family'), hasText: 'MAT-990001' },
        target: 'button', text: 'Use this', untilText: 'Using MAT-990001' },
      { say: 'Now the six millimetre sheet shows it too: in Stock, on PR lines and in the search palette. Every change is audited.',
        do: 'point', target: tid('catalogue-image'), timeout: 20_000 },
      { say: 'When the size matters, a real photo replaces it. Remove keeps the picture, so it can be restored.',
        do: 'click', target: tid('catalogue-remove'), until: '.ant-popconfirm' },
      { say: 'Confirm.', do: 'click', target: '.ant-popconfirm .ant-btn-primary', until: tid('catalogue-restore'), timeout: 20_000 },
      { say: 'Pictures live on this machine, are backed up every night, and are never fetched from the web.' },
    ],
  },
  {
    id: 'form-print',
    title: 'Print a consumption form for a lining system',
    blurb: 'Choose a lining system; the form lists its materials, each sheet is numbered with a QR code, and the filled form comes back as a photo.',
    roles: ['supervisor', 'hod', 'admin'],
    beats: [
      { say: 'This demo runs on Practice data. It stops before the download, so no form number is used up.' },
      { say: 'We start as the site supervisor.', do: 'switch', value: 'supervisor' },
      { say: 'Execution. The form for the crew is printed here.', do: 'navigate', value: '/execution',
        until: tid('form-print-system'), timeout: 30_000 },
      { say: 'Choose the lining system the crew will apply.', do: 'select', target: tid('form-print-system'), value: '—' },
      { say: 'The form lists that system’s materials, in recipe order, so the crew writes quantities, not names.' },
      { say: 'Forms counts forms, not pages: a long system takes more than one sheet, and the line under it says how many.' },
      { say: 'Download makes the PDF. Every form is a new numbered sheet with its own QR code, so a filled form photographed later is matched to the system it was printed for.',
        do: 'point', target: tid('form-print-download') },
      { say: 'When the crew has filled it, the supervisor photographs the whole page, QR code included, and uploads it here. The local AI reads it, and the store keeper checks the quantities.',
        do: 'point', target: tid('form-upload-card'), optional: true, timeout: 5000 },
      { say: 'An Admin, who belongs to no single site, chooses the site first. That was the cause of the old print error.' },
    ],
  },
  {
    id: 'assistant-voice',
    title: 'Ask the Hub Assistant by voice; hear the answer',
    blurb: 'Dictate a question on this computer, read it, send it; the answer can be read aloud.',
    roles: ['store_keeper', 'supervisor', 'hod', 'qc', 'logistics', 'admin'],
    beats: [
      { say: 'This demo shows voice. Speech is turned into text on this computer: no recording leaves the site.' },
      { say: 'Open the Hub Assistant.', do: 'click', target: 'button[aria-label="Open Hub Assistant"]',
        until: 'input[placeholder="Ask the manual…"]' },
      { say: 'The microphone: press it, speak, press it again. The words land in the box.',
        do: 'point', target: tid('assistant-mic'), optional: true, timeout: 4000 },
      { say: 'Nothing is sent by speaking. You read the words, fix any, and press Send.',
        do: 'type', target: 'input[placeholder="Ask the manual…"]', value: 'How do I stage a return?' },
      { say: 'Send.', do: 'click', target: 'button[aria-label="Send"]' },
      { say: 'Each answer has a speaker button. It reads the answer aloud in this device’s own voice.',
        do: 'point', target: tid('assistant-read-aloud'), optional: true, timeout: 40_000 },
      { say: 'The same two controls sit in the top bar for every page: read this page aloud, and dictate into the box you were typing in.',
        do: 'point', target: tid('voice-bar'), optional: true, timeout: 3000 },
      { say: 'Voice is English only, and needs nothing installed on the phone or laptop.' },
    ],
  },
  {
    id: 'return-dn',
    title: 'A return to the vendor, with its return DN',
    blurb: 'The store keeper returns part of a delivery against its receipt, with the return DN; the HOD approves.',
    roles: ['store_keeper', 'hod', 'admin'],
    vars: () => ({ ref: stamp() }),
    beats: [
      { say: 'This demo runs on Practice data. The return DN carries a DEMO tag, so Reset demo data removes it.' },
      { say: 'We start as the store keeper.', do: 'switch', value: 'store_keeper' },
      { say: 'Return Stock.', do: 'navigate', value: '/entry/return',
        until: 'input[placeholder="delivery-note number"]' },
      { say: 'The material going back: gasket sets.', do: 'select', target: '#SAP_Code', value: '899001' },
      { say: 'A return is made against a receipt. GI Hub lists this material’s receipts of the last thirty days; this one came on delivery note 90001.',
        do: 'select', target: '#source_receipt_id', value: '90001', timeout: 20_000 },
      { say: 'One set goes back. It can never be more than the receipt brought.', do: 'type', target: '#Quantity', value: '1' },
      { say: 'Why.', do: 'select', target: '#Reason', value: 'overstock' },
      { say: 'The return DN: the note that travels back with the goods.', do: 'type',
        target: 'input[placeholder="delivery-note number"]', value: '{ref}' },
      { say: 'And its paper. The demo attaches a practice slip.', do: 'attach', target: tid('entry-docs'),
        value: '{ref}', untilText: '{ref}.png' },
      { say: 'Post the return. It waits for the HOD.', do: 'click', target: 'button', text: 'Post return',
        untilText: 'Return submitted for HOD approval' },
      { say: 'Now the HOD.', do: 'switch', value: 'hod' },
      { say: 'Approvals.', do: 'navigate', value: '/hod/approvals', until: '.ant-tabs-tab' },
      { say: 'Returns.', do: 'click', target: '.ant-tabs-tab', text: 'Returns' },
      { say: 'The return, with its return DN and its paper.', do: 'point',
        within: { css: '.ant-table-row', hasText: '{ref}' }, timeout: 20_000 },
      { say: 'The HOD approves it.', do: 'click', within: { css: '.ant-table-row', hasText: '{ref}' },
        target: 'button', text: 'Approve' },
      { say: 'And confirms.', do: 'click', target: '.ant-popconfirm .ant-btn-primary', untilText: 'Approved' },
      { say: 'Records, Returns.', do: 'navigate', value: '/records/returns',
        until: 'input[placeholder="Search SAP code / name…"]' },
      { say: 'We look it up.', do: 'type', target: 'input[placeholder="Search SAP code / name…"]', value: '{ref}', enter: true },
      { say: 'In the ledger, the return names its return DN, for anyone who asks where the goods went.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' }, timeout: 20_000 },
      { say: 'Goods out of the store, on paper, against the delivery they came on.' },
    ],
  },
  {
    id: 'reorder-requests',
    title: 'Smart Reorder, and requests without a PR',
    blurb: 'What to order and why — counting what is on order and what was requested without a PR.',
    roles: ['hod', 'logistics', 'admin'],
    beats: [
      { say: 'This demo runs on Practice data, and only looks.' },
      { say: 'We start as the HOD.', do: 'switch', value: 'hod' },
      { say: 'Stock, reorder signals.', do: 'navigate', value: '/stock?tab=reorder',
        until: tid('reorder-signals'), timeout: 30_000 },
      { say: 'Every item under its minimum, and how much to order to bring it back to twice the minimum.',
        do: 'point', target: tid('reorder-signals') },
      { say: 'On order counts what this site’s open POs will bring.', do: 'point', target: tid('global-on-order'),
        optional: true, timeout: 5000 },
      { say: 'Requested, no PR, is material asked for in a request workbook that has not arrived. It is taken off the suggested order, so it is not ordered twice.',
        do: 'point', target: tid('requested-no-pr'), optional: true, timeout: 5000 },
      { say: 'Those requests are listed in Requests and Pending.', do: 'navigate', value: '/requests-pending',
        until: tid('req-table'), timeout: 30_000 },
      { say: 'What was asked for, what arrived, and what is still open, line by line.', do: 'point', target: tid('req-table') },
      { say: 'A request line with no SAP code counts against nothing until somebody links it, above.',
        do: 'point', target: tid('req-needs-sap'), optional: true },
      { say: 'The order suggested is the order needed: minus what is coming, and minus what was asked for.' },
    ],
  },
  {
    id: 'management-tour',
    title: 'Management tour: GI Hub in one walk-through',
    blurb: 'A walk through GI Hub for management: stock, requests, pictures, lots, execution, approvals.',
    roles: ['hod', 'logistics', 'admin'],
    beats: [
      { say: 'This is a tour of GI Hub, on Practice data. Every number on these screens is made up.' },
      { say: 'We sign in as the Head of Department.', do: 'switch', value: 'hod' },
      { say: 'The dashboard: the site’s stock, what is expiring, and what waits for a decision.', do: 'navigate',
        value: '/', until: '.ant-card', timeout: 30_000 },
      { say: 'The chip in the top bar says how fresh the data is. Live pulls the site workbooks from Google Drive on a schedule.',
        do: 'point', target: tid('drive-freshness'), optional: true },
      { say: 'Stock, reorder signals: every item under its minimum, the order that brings it back, and the working behind it.',
        do: 'navigate', value: '/stock?tab=reorder', until: tid('reorder-signals'), timeout: 30_000 },
      { say: 'Requests and Pending: each request workbook, line by line, against what arrived.', do: 'navigate',
        value: '/requests-pending', until: tid('req-table'), timeout: 30_000 },
      { say: 'Lines with no SAP code are linked here, once, and remembered.', do: 'point', target: tid('req-needs-sap'),
        optional: true },
      { say: 'The catalogue: the company’s material codes, with pictures, so a PR says exactly what to buy.',
        do: 'navigate', value: '/catalogue', until: tid('catalogue-search'), timeout: 30_000 },
      { say: 'Lots and Expiry: every batch, its expiry, and its certificate. The earliest expiry is issued first.',
        do: 'navigate', value: '/lots', until: tid('lot-table'), timeout: 30_000 },
      { say: 'Execution: the lining done each day, tank by tank, with the material it drew.', do: 'navigate',
        value: '/execution', until: '.ant-tabs-tab', timeout: 30_000 },
      { say: 'Approvals: nothing reaches the stock ledger until the HOD approves it.', do: 'navigate',
        value: '/hod/approvals', until: '.ant-tabs-tab', timeout: 30_000 },
      { say: 'Purchase requests: raised here, with pictures, and handed to Logistics.', do: 'navigate',
        value: '/hod/prs', until: '.ant-tabs-tab', timeout: 30_000 },
      { say: 'Papers are read by a local AI, questions are answered by voice, and nothing leaves the company’s own machine.' },
      { say: 'That is GI Hub: one record of the store, checked once, and visible to everyone who needs it.' },
    ],
  },
]

export const scriptById = (id: string) => SCRIPTS.find((s) => s.id === id)
