/**
 * Phase 21f — the self-driving demos (flows 1 and 2, ruling Q21-14: the
 * Finance story first). Each one is ALSO an E2E spec in the Practice leg
 * (tests/e2e/specs/demo.spec.ts), so a demo that would stall in front of
 * management fails a pull request first.
 *
 * Kept in step with `backend/api/practice_demo.CATALOG` (ids, titles, roles),
 * which the assistant reads to offer a demo — suite 21F checks they agree.
 *
 * ⚠️ Every entry a demo makes carries `DEMO-` (the remark, or the DEMO- tank),
 * so Reset demo data (HOD / Admin) removes exactly what demos made (Q21-17).
 * No supplier prices and no real site names in a sentence (Q20-17).
 */
import { tid } from './types'
import type { DemoScript } from './types'

const stamp = () => {
  const d = new Date()
  const p = (n: number) => String(n).padStart(2, '0')
  return `DEMO-${p(d.getDate())}${p(d.getMonth() + 1)}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`
}

export const DEMO_TANK = 'DEMO-TANK-1'

const p2 = (n: number) => String(n).padStart(2, '0')
const iso = (d: Date) => `${d.getFullYear()}-${p2(d.getMonth() + 1)}-${p2(d.getDate())}`
const ddmmyy = (d: Date) => `${p2(d.getDate())}/${p2(d.getMonth() + 1)}/${p2(d.getFullYear() % 100)}`
/** A paper date with the MONTH misread: the day is right, the month is six
 *  months off — the 01/07/26-for-01/10/26 case the real photos produced. */
const misreadToday = () => {
  const d = new Date()
  return `${p2(d.getDate())}/${p2(((d.getMonth() + 6) % 12) + 1)}/${p2(d.getFullYear() % 100)}`
}

export const SCRIPTS: DemoScript[] = [
  {
    id: 'consumption-to-approval',
    title: 'Issue stock, then the HOD approves it',
    blurb: 'The store keeper records an issue with its paper; the HOD approves it into the ledger.',
    roles: ['store_keeper', 'hod', 'admin'],
    vars: () => ({ ref: stamp() }),
    beats: [
      { say: 'This demo runs on Practice data. Nothing here touches the live warehouse.' },
      { say: 'We start as the store keeper, at the warehouse counter.', do: 'switch', value: 'store_keeper' },
      { say: 'This is Issue Stock. Everything that leaves the store is written here first.',
        do: 'navigate', value: '/entry/issue', until: '#SAP_Code' },
      { say: 'First the material. The store keeper finds it by name, not by code.',
        do: 'select', target: '#SAP_Code', value: 'Masking Tape', as: 'item' },
      { say: 'The line under it shows what is in stock right now, and how many days that lasts.',
        do: 'point', target: tid('item-snapshot'), optional: true, timeout: 5000 },
      { say: 'Two of them left the store today.', do: 'type', target: '#Quantity', value: '2' },
      { say: 'The work package it is charged to.', do: 'select', target: '#wbs', value: 'WBS',
        optional: true, timeout: 3000 },
      { say: 'Who received it.', do: 'type', target: '#Issued_To', value: 'Crew A' },
      { say: 'The remark carries a DEMO tag, so a trainer can clear this entry afterwards.',
        do: 'type', target: '#Remarks', value: '{ref} practice demo' },
      { say: 'Add to batch. A store keeper can add many lines and send them together.',
        do: 'click', target: 'button', text: 'Add to batch', untilText: 'Batch (1 line)' },
      { say: 'Every entry carries its paper. The demo attaches a practice slip, as you would attach a photo of the note.',
        do: 'attach', target: tid('entry-docs'), value: '{ref}', untilText: '{ref}.png' },
      { say: 'Submit the batch to the HOD.', do: 'click', target: 'button', text: 'Submit batch to HOD',
        untilText: 'submitted for HOD approval' },
      { say: 'Nothing has left the ledger yet. It waits for the HOD.' },
      { say: 'Now we sign out, and sign in as the HOD.', do: 'switch', value: 'hod' },
      { say: 'The HOD opens Approvals: everything the site has submitted, by kind.',
        do: 'navigate', value: '/hod/approvals', until: '.ant-tabs-tab' },
      { say: 'Issues.', do: 'click', target: '.ant-tabs-tab', text: 'Issues' },
      { say: 'Here is the store keeper’s line, with its DEMO tag. The analysis under it compares the draw with this material’s usual use.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' } },
      { say: 'The HOD approves it.', do: 'click', within: { css: '.ant-table-row', hasText: '{ref}' },
        target: 'button', text: 'Approve' },
      { say: 'And confirms. Approval commits it to the ledger: the stock figure changes now, and the audit log records who approved it.',
        do: 'click', target: '.ant-popconfirm .ant-btn-primary', untilText: 'Approved' },
      { say: 'That is the loop: written once at the counter, checked once by the HOD, and in the stock figure the moment it is approved.' },
    ],
  },
  {
    id: 'ss-bulk',
    title: 'Surface Shield jobs: bulk submit, then bulk approve',
    blurb: 'The supervisor files a week of lining jobs in one go; the HOD approves them in one go.',
    roles: ['store_keeper', 'supervisor', 'hod', 'admin'],
    vars: () => ({ tank: DEMO_TANK }),
    beats: [
      { say: 'This demo runs on Practice data, on a demo tank kept for it.' },
      { say: 'We start as the site supervisor, who files the lining work done each day.',
        do: 'switch', value: 'supervisor' },
      { say: 'Execution. Each card is one day of Surface Shield material drawn for one tank.',
        do: 'navigate', value: '/execution', until: 'input[aria-label="Find a job"]' },
      { say: 'We look at the demo tank.', do: 'type', target: 'input[aria-label="Find a job"]', value: '{tank}' },
      { say: 'A card is ready when the store keeper’s remark gives the area. The supervisor checks it; nothing is typed twice.',
        do: 'point', within: { css: '.gi-job-card', hasText: '{tank}' } },
      { say: 'Select all ready picks every complete card.', do: 'click', target: tid('bulk-select-ready') },
      { say: 'One review of the whole batch: the days, the tanks, the total area.',
        do: 'click', target: tid('bulk-submit'), until: tid('bulk-submit-confirm') },
      { say: 'And one click sends them all to the HOD.', do: 'click', target: tid('bulk-submit-confirm'),
        untilText: 'Submitted' },
      { say: 'Now we sign out, and sign in as the HOD.', do: 'switch', value: 'hod' },
      { say: 'The HOD opens the same page.', do: 'navigate', value: '/execution', until: '.ant-tabs-tab' },
      { say: 'Awaiting the HOD: every job submitted from the site.', do: 'click', target: '.ant-tabs-tab',
        text: 'Awaiting the HOD' },
      { say: 'The HOD ticks the demo tank’s jobs.', do: 'check',
        within: { css: '.gi-job-card', hasText: '{tank}' }, target: 'input[type=checkbox]' },
      { say: 'Approve selected. The confirmation shows the total area, and names any job drawn more than ten percent off the recipe before the click.',
        do: 'click', target: tid('hod-approve-selected'), until: tid('hod-approve-confirm') },
      { say: 'Approved. Each job’s area is credited to the tank once, and the material it drew is recorded against it.',
        do: 'click', target: tid('hod-approve-confirm'), untilText: 'Approved' },
      { say: 'A week of lining, filed and approved in two clicks each — with every number still checked.' },
    ],
  },
  {
    id: 'receive-lot',
    title: 'Receive a batch with its MFD; it appears in Lots & Expiry',
    blurb: 'A lot-tracked material is received with its batch number and manufacture date; the expiry is worked out, and FEFO knows it.',
    roles: ['store_keeper', 'hod', 'admin'],
    vars: () => ({ ref: stamp(), mfd: iso(new Date(Date.now() - 20 * 86_400_000)) }),
    beats: [
      { say: 'This demo runs on Practice data: a delivery of lining primer arrives at the store.' },
      { say: 'We start as the store keeper.', do: 'switch', value: 'store_keeper' },
      { say: 'Receive Stock. Goods are recorded here, with their paper.',
        do: 'navigate', value: '/entry/receive', until: '#SAP_Code' },
      { say: 'The material: a lot-tracked primer. Lot-tracked items ask for their batch and dates.',
        do: 'select', target: '#SAP_Code', value: 'PRACTICE PU PRIMER' },
      { say: 'Four cans.', do: 'type', target: '#Quantity', value: '4' },
      { say: 'The batch number, as printed on the can. This one carries a DEMO tag.',
        do: 'type', target: '#Lot_Number', value: '{ref}' },
      { say: 'The manufacture date from the label.', do: 'type', target: '#MFD_Date', value: '{mfd}', enter: true },
      { say: 'Leave the expiry blank: it is worked out from the manufacture date and the shelf life.',
        do: 'point', target: '#Expiry_Date', untilText: 'Leave blank', optional: true },
      { say: 'The work package.', do: 'select', target: '#wbs', value: 'WBS', optional: true, timeout: 3000 },
      { say: 'Who it came from.', do: 'type', target: '#Supplier', value: 'Practice supplier' },
      { say: 'And a DEMO remark.', do: 'type', target: '#Remarks', value: '{ref} practice demo' },
      { say: 'Add to batch.', do: 'click', target: 'button', text: 'Add to batch', untilText: 'Batch (1 line)' },
      { say: 'The delivery note goes with it: the demo attaches a practice slip.',
        do: 'attach', target: tid('entry-docs'), value: '{ref}', untilText: '{ref}.png' },
      { say: 'Submit the batch to the HOD.', do: 'click', target: 'button', text: 'Submit batch to HOD',
        untilText: 'submitted for HOD approval' },
      { say: 'Now the HOD.', do: 'switch', value: 'hod' },
      { say: 'Approvals, receipts.', do: 'navigate', value: '/hod/approvals', until: '.ant-tabs-tab' },
      { say: 'Receipts.', do: 'click', target: '.ant-tabs-tab', text: 'Receipts' },
      { say: 'The delivery, with its batch number.', do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' } },
      { say: 'The HOD approves it.', do: 'click', within: { css: '.ant-table-row', hasText: '{ref}' },
        target: 'button', text: 'Approve' },
      { say: 'And confirms.', do: 'click', target: '.ant-popconfirm .ant-btn-primary', untilText: 'Approved' },
      { say: 'Lots and Expiry: every batch on site, with its expiry and what is left of it.',
        do: 'navigate', value: '/lots', until: tid('lot-table'), timeout: 30_000 },
      { say: 'We look up the new batch.', do: 'type', target: 'input[aria-label="Find a lot"]', value: '{ref}', enter: true,
        timeout: 30_000 },
      { say: 'There it is, with the expiry worked out. When primer is issued, the earliest expiry is picked first.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' }, timeout: 40_000 },
      { say: 'From the label on the can to the expiry list, with nothing typed twice.' },
    ],
  },
  {
    id: 'loan-partial',
    title: 'Lend a tool, and take part of it back',
    blurb: 'Three clamp sets go out on loan; one comes back. The loan stays open and says what is still out.',
    roles: ['store_keeper', 'hod', 'admin'],
    vars: () => ({ ref: stamp() }),
    beats: [
      { say: 'This demo runs on Practice data: tools lent to the field.' },
      { say: 'We start as the store keeper.', do: 'switch', value: 'store_keeper' },
      { say: 'Returnable Items: the loan desk.', do: 'navigate', value: '/entry/returnables',
        until: tid('return-scan-input') },
      { say: 'Lend a tool.', do: 'click', target: 'button', text: 'Loan a tool', until: '.ant-modal' },
      { say: 'Scan the tool’s sticker. The demo types the code instead of using the camera.',
        do: 'click', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' }, target: 'button', text: 'Scan tool' },
      { say: 'The code.', do: 'type', within: { css: '.ant-modal', hasText: 'Scan the tool' },
        target: 'input[placeholder="…or type the code"]', value: '{ref}', enter: true, untilText: 'Scanned: {ref}' },
      { say: 'What it is.', do: 'type', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' },
        target: 'input[placeholder="e.g. Torque wrench — or Scan tool ↑"]', value: 'Clamp set (demo)' },
      { say: 'Who takes it.', do: 'type', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' },
        target: 'input[placeholder="Employee name — or Scan badge ↑"]', value: '{ref} crew' },
      { say: 'Three of them.', do: 'type', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' },
        target: '.ant-input-number input', value: '3' },
      { say: 'Due back in three days.', do: 'click', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' },
        target: 'button', text: '+3 days' },
      { say: 'Record the loan.', do: 'click', within: { css: '.ant-modal', hasText: 'Loan a tool to an employee' },
        target: 'button', text: 'Record loan', untilText: 'Loan recorded' },
      { say: 'Later, one clamp set comes back. The desk takes a scan of the sticker.',
        do: 'type', target: tid('return-scan-input'), value: '{ref}', enter: true, until: tid('return-panel') },
      { say: 'One back, not three.', do: 'type', within: { css: tid('return-panel'), hasText: 'Clamp set' },
        target: '[data-testid^="return-qty-"]', value: '1' },
      { say: 'Confirm the return.', do: 'click', target: tid('return-confirm'), untilText: '2 still out' },
      { say: 'The loan stays open and says two are still out. Overdue loans are chased automatically.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' }, target: '[data-testid^="loan-partial-"]' },
      { say: 'Slip prints the borrower’s slip. Its QR code finds this loan in one scan.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' }, target: '[data-testid^="loan-slip-"]', optional: true },
      { say: 'Nothing lent is forgotten, and nothing returned is counted twice.' },
    ],
  },
  {
    id: 'reorder-pace',
    title: "Set the site's SQM pace, then accept a minimum",
    blurb: 'The HOD plans how fast the site lines, and the Surface Shield minimums follow; then accepts one.',
    roles: ['hod', 'admin'],
    beats: [
      { say: 'This demo runs on Practice data. Reset demo data puts the pace and the minimum back afterwards.' },
      { say: 'We start as the HOD.', do: 'switch', value: 'hod' },
      { say: 'Stock, reorder signals: what to order, and why.', do: 'navigate', value: '/stock?tab=reorder',
        until: tid('reorder-signals') },
      { say: 'This note is the site: the area still to line, and the pace the minimums are planned on.',
        do: 'point', target: '[data-testid^="pace-note-"]' },
      { say: 'The HOD sets the pace.', do: 'click', target: '[data-testid^="pace-set-"]', until: tid('pace-input') },
      { say: 'A suggestion from the site’s own approved jobs.', do: 'point', target: tid('pace-suggestion'), optional: true },
      { say: 'Six square metres a day.', do: 'type', target: tid('pace-input'), value: '6' },
      { say: 'Save. Every Surface Shield minimum is worked out again from it.', do: 'click', target: tid('pace-save'),
        untilText: 'planned pace' },
      { say: 'We look at the lining primer.', do: 'type', target: 'input[placeholder="SAP, material code or name"]',
        value: 'PRACTICE PU PRIMER', enter: true },
      { say: 'How? shows the working: area, rate, days of cover, pack size.', do: 'point', target: tid('math-trail'), optional: true },
      { say: 'Review minimums.', do: 'click', target: tid('min-review'), until: tid('min-accept') },
      { say: 'The HOD ticks the primer.', do: 'check', within: { css: '.ant-table-row', hasText: 'PRACTICE PU PRIMER' },
        target: 'input[type=checkbox]' },
      { say: 'And accepts its minimum. It is the site’s until the HOD accepts another.',
        do: 'click', target: tid('min-accept'), until: tid('min-accepted') },
      { say: 'The minimum now follows the work actually planned, and the order brings stock back to twice it.' },
    ],
  },
  {
    id: 'ocr-paste',
    title: 'A consumption paper: date check, names, stage',
    blurb: 'A handwritten paper with a misread date and a misspelt name, checked and staged for the HOD.',
    roles: ['store_keeper', 'hod', 'admin'],
    vars: () => ({ ref: stamp(), paper: misreadToday(), today: ddmmyy(new Date()) }),
    beats: [
      { say: 'This demo runs on Practice data: a consumption paper, as the reader would read it.' },
      { say: 'We start as the store keeper.', do: 'switch', value: 'store_keeper' },
      { say: 'OCR Import. A photo goes to the local AI; this demo uses the paste box, which gives the same result.',
        do: 'navigate', value: '/entry/ocr', until: 'textarea' },
      { say: 'The paper, as read: its date, and two lines.', do: 'type', target: 'textarea',
        value: 'Date: {paper}\n{ref}, Nitril glovs, Pair, 2, PV\n{ref}, Safty goggls, Nos, 1, RIL' },
      { say: 'Parse.', do: 'click', target: 'button', text: 'Parse', until: tid('ocr-date-check') },
      { say: 'The date reads {paper}: months from today. The reader misread it, so it is not taken.',
        do: 'point', target: tid('ocr-date-check') },
      { say: 'The first suggestion keeps the day and fixes the month: {today}.', do: 'click',
        target: tid('ocr-date-candidate') },
      { say: 'Nitril glovs is green: a store keeper here taught the matcher that name.',
        do: 'point', target: tid('ocr-state-auto'), optional: true },
      { say: 'Safty goggls is gold: a suggestion. Nothing gold is filled in by itself.',
        do: 'point', target: tid('ocr-suggestion'), optional: true },
      { say: 'Accept teaches it. Next time it is green.', do: 'click', target: tid('ocr-accept'), optional: true },
      { say: 'The work type is in the workbook’s spelling: PV became PU.', do: 'point', target: tid('ocr-work-type') },
      { say: 'The paper itself is the supporting document. A photographed page is attached by itself; here the demo attaches a practice slip.',
        do: 'attach', target: tid('entry-docs'), value: '{ref}', untilText: '{ref}.png' },
      { say: 'The work package.', do: 'select', target: tid('ocr-wbs'), value: 'WBS', optional: true, timeout: 3000 },
      { say: 'Stage the rows for the HOD.', do: 'click', target: tid('ocr-stage'), until: '.ant-popconfirm' },
      { say: 'Confirm.', do: 'click', target: '.ant-popconfirm .ant-btn-primary', untilText: 'staged for HOD approval' },
      { say: 'Now the HOD.', do: 'switch', value: 'hod' },
      { say: 'Approvals, issues.', do: 'navigate', value: '/hod/approvals', until: '.ant-tabs-tab' },
      { say: 'Issues.', do: 'click', target: '.ant-tabs-tab', text: 'Issues' },
      { say: 'The paper’s lines wait here like any issue, on the date the store keeper confirmed.',
        do: 'point', within: { css: '.ant-table-row', hasText: '{ref}' } },
      { say: 'A paper read in minutes, with every doubtful field put in front of a person.' },
    ],
  },
]

export const scriptById = (id: string) => SCRIPTS.find((s) => s.id === id)
