"""
tools/gen_semantic_bank.py — the labelled examples behind the Phase 19d
semantic safety signal (backend/api/ai/semantic.py).

    .venv/bin/python tools/gen_semantic_bank.py           # write the bank
    .venv/bin/python tools/gen_semantic_bank.py --check   # exit 1 if stale

The bank is the router's DEV security set (attacks and their negative twins)
plus the routing set (ordinary questions, labelled benign). It is GENERATED so
it can never drift from the eval files it is measured against, and it is
written to backend/ so a deployed box (which ships no tests/) has it.

⚠️ NEVER A HOLDOUT (P17-D3, P18-blind). `security_holdout.yaml` and the
operator's blind v2 measure how the defences GENERALISE. A holdout case in the
bank would match itself and turn that number into theatre. Suite 19D asserts
that no holdout prompt is in the bank.

Only the TEXT is stored, never the vectors. They are computed at runtime by
the embedding model actually deployed, so a model update can never leave
stale vectors behind.
"""
from __future__ import annotations

import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "tests" / "ai_eval" / "router"
OUT = ROOT / "backend" / "api" / "ai" / "semantic_bank.json"


def build() -> dict:
    dev = yaml.safe_load((SRC / "security.yaml").read_text(encoding="utf-8")) or []
    routing = yaml.safe_load((SRC / "routing.yaml").read_text(encoding="utf-8")) or []
    items = [{"id": c["id"], "label": "attack" if not c["safe"] else "twin",
              "text": c["prompt"]} for c in dev]
    items += [{"id": c["id"], "label": "benign", "text": c["prompt"]} for c in routing]
    return {"_note": "GENERATED by tools/gen_semantic_bank.py from the router DEV set + "
                     "the routing set. Never a holdout. Do not edit by hand.",
            "items": items}


def main(argv: list[str]) -> int:
    text = json.dumps(build(), ensure_ascii=False, indent=1) + "\n"
    if "--check" in argv:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            print("❌ semantic_bank.json is stale — run tools/gen_semantic_bank.py")
            return 1
        print(f"✅ semantic_bank.json is current — {len(build()['items'])} examples")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(build()['items'])} examples")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
