"""
ai/manual_qa.py — Role-aware Q&A over USER_MANUAL.md
=====================================================
Lets every signed-in user ask the Hub Assistant a question; the answer is
generated by the local llama3.1:8b model using ONLY the sections of
USER_MANUAL.md that match the user's role.

Why role-filter the context (not just the system prompt)?
  Because a system prompt is a request, not a guarantee. If a Store
  Keeper asks "how do I delete users?", we don't want to give the model
  the Admin chapter at all — that way it physically cannot leak the
  answer. The role gate happens at the RAG layer.

Public API
----------
    answer_manual_question(question: str, role: str) -> Iterator[str]
        Yields token chunks. Errors yield a single string with a friendly
        hint instead of raising — so the UI never breaks.

    health() -> tuple[bool, str]
        Returns (ok, msg). Used by main.py to render the right empty-state.
"""

from __future__ import annotations

import os
import re
from functools import lru_cache
from pathlib import Path
from typing import Iterator

from ai.client import (
    MODEL_CHAT,
    OLLAMA_HOST,
    list_ollama_models,
    ollama_health,
    ollama_stream,
)


# ---------------------------------------------------------------------------
# Role-section allow-list — which top-level USER_MANUAL.md sections each
# role is allowed to see in their context. Lower roles cannot see higher
# roles' sections.
# ---------------------------------------------------------------------------
_ROLE_ALLOWED: dict[str, set[int]] = {
    # Site-level roles see their own chapter + universal preamble + glossary/FAQ.
    "store_keeper":   {1, 2, 3, 4, 10, 11, 12, 13},
    "supervisor":     {1, 2, 3, 4, 5, 11, 12, 13},
    "hod":            {1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 16},
    # Procurement-chain roles — own portal + cross-role walkthrough.
    # Strict isolation: Logistics never sees Warehouse internals (and vice versa);
    # neither sees site-level chapters 4–6.
    "logistics":      {1, 2, 3, 9, 11, 12, 13, 14, 16},
    "warehouse_user": {1, 2, 3, 9, 11, 12, 13, 15, 16},
    # Admin sees everything — full range §1..§17. Combined with the
    # full-section (no-truncation) special case in _context_for_role, Admin
    # gets deep-content answers (e.g. "how to add users" lives in §7.6, far
    # past the 800-char head used for other roles).
    "admin":          set(range(1, 18)),
}

# Section number → friendly title (used to label context in the prompt)
_SECTION_TITLES = {
    1:  "Introduction & System Overview",
    2:  "Roles, Permissions & Page Access",
    3:  "Login, Sidebar & Common Elements",
    4:  "Store Keeper Manual",
    5:  "Supervisor Manual",
    6:  "HOD Manual",
    7:  "Admin Manual",
    8:  "Reports Module",
    9:  "Automated Notifications (WhatsApp + Email)",
    10: "Data Model & Concept Reference",
    11: "Status Codes, Reason Codes & Glossary",
    12: "FAQ — Master Index",
    13: "2026-06 Feature Update",
    14: "Logistics Portal Manual",
    15: "Warehouse Portal Manual",
    16: "Cross-Role Procurement Walk-through",
    17: "Operations & Hosting",
}


# ---------------------------------------------------------------------------
# Manual loading + section split
# ---------------------------------------------------------------------------
def _manual_path() -> Path:
    """Where USER_MANUAL.md lives — overridable for tests."""
    return Path(os.environ.get("GI_USER_MANUAL_PATH", "USER_MANUAL.md"))


@lru_cache(maxsize=1)
def _load_sections() -> dict[int, str]:
    """
    Parse USER_MANUAL.md once, return {section_number: full_section_text}.
    Section boundaries are top-level "# N. " headings, EXCEPT for the
    cover-page H1 "# General Industries Hub …" which has no leading number.
    """
    path = _manual_path()
    if not path.exists():
        return {}
    md = path.read_text(encoding="utf-8")

    # Split on `^# N. ` style headings — kept inclusive via a lookbehind.
    parts = re.split(r"(?m)^(?=# \d+\.\s+)", md)
    out: dict[int, str] = {}
    for chunk in parts:
        m = re.match(r"# (\d+)\.\s+(.*?)\n", chunk)
        if not m:
            continue
        num = int(m.group(1))
        out[num] = chunk.strip()
    return out


_PER_SECTION_CHAR_CAP = 800   # was 3000 — keeps total prompt under ~3K tokens


@lru_cache(maxsize=16)
def _context_for_role(role: str) -> str:
    """
    Build the RAG context: concatenation of allowed sections, each prefixed
    with a clear delimiter and section label so the LLM knows what's what.

    Truncation policy (Phase 7G — AI sidebar context fix):
      - Admin: FULL sections, no truncation. Trade-off: ~20-30s slower first
        response, fast after that (Ollama keep_alive caches the KV). Worth
        it — Admin asks rare, deep operational questions like "how to add
        users" where the answer lives 150 lines past the section head.
      - Every other role: head-truncated at _PER_SECTION_CHAR_CAP. Site
        users ask short workflow questions; the head covers them.

    Cached per-role so the string is computed once per process — combined
    with Ollama's keep_alive KV cache (see ai/client.py) this means the
    system prompt's KV state is reused across messages.
    """
    allowed = _ROLE_ALLOWED.get(role, _ROLE_ALLOWED["store_keeper"])
    sections = _load_sections()
    if not sections:
        return ""

    is_admin = role == "admin"
    chunks = []
    for num in sorted(allowed):
        body = sections.get(num)
        if not body:
            continue
        if not is_admin and len(body) > _PER_SECTION_CHAR_CAP:
            body = body[:_PER_SECTION_CHAR_CAP] + "\n[... truncated — ask for specifics if you need more ...]"
        chunks.append(f"=== Section {num}: {_SECTION_TITLES.get(num, '')} ===\n{body}")
    return "\n\n".join(chunks)


# ---------------------------------------------------------------------------
# Greeting fast-path — never call the LLM for trivial pleasantries.
# Saves ~30s of prompt-eval for every "Hi" / "thanks" message.
# ---------------------------------------------------------------------------
_GREETING_TOKENS = {
    "hi", "hii", "hello", "hey", "heya", "yo", "hola",
    "thanks", "thank you", "ty", "thx",
    "ok", "okay", "cool", "great", "nice",
    "bye", "goodbye", "cya", "see you",
    "good morning", "good afternoon", "good evening", "morning", "evening",
}


def _greeting_reply(question: str) -> str | None:
    """Return a canned reply if the question is a trivial greeting, else None."""
    q = re.sub(r"[!?.,…]+$", "", (question or "").strip().lower())
    if not q or len(q) > 24:
        return None
    if q in _GREETING_TOKENS:
        if q.startswith("thank") or q in {"ty", "thx"}:
            return "You're welcome — ask me anything from your section of the manual."
        if q in {"bye", "goodbye", "cya", "see you"}:
            return "Goodbye! I'll be here when you need me."
        if q in {"ok", "okay", "cool", "great", "nice"}:
            return "👍 Anything else from the manual you'd like me to look up?"
        return "Hi! I'm the Hub Assistant. Ask me anything about your role's section of the manual."
    return None


# ---------------------------------------------------------------------------
# Prompt construction
# ---------------------------------------------------------------------------
_ROLE_LABEL = {
    "store_keeper":   "Store Keeper",
    "supervisor":     "Supervisor",
    "hod":            "Head of Department",
    "logistics":      "Logistics Coordinator",
    "warehouse_user": "Warehouse Operator",
    "admin":          "Administrator",
}

# Role-aware refusal phrasing — replaces the previous "ask your HOD or
# Admin" boilerplate that read as condescending when Admin was the asker.
# Each phrase quotes the user's role so the LLM stays grounded in who it
# is talking to (reinforces the {username} / {role_label} prelude).
_ROLE_REFUSAL = {
    "store_keeper":   "That's not in your section of the manual — please escalate to your HOD.",
    "supervisor":     "That's not in your section of the manual — please escalate to your HOD.",
    "hod":            "That's in the Admin chapter — please ask your Admin.",
    "logistics":      "That's outside the Logistics Portal — please ask your Admin.",
    "warehouse_user": "That's outside the Warehouse Portal — please ask your Admin.",
    "admin":          "I can't find that in the manual. Try Admin Portal → Settings → 📥 Download Role Manuals for the latest reference, or check the source markdown in USER_MANUAL.md.",
}

_SYSTEM_PROMPT_TMPL = """\
You are the Hub Assistant, a documentation helper for the General \
Industries Hub warehouse system. You are talking to {username}, a {role_label}.

RULES:
- Answer ONLY using the manual sections provided below as CONTEXT.
- If the answer is not in the CONTEXT, reply with exactly this sentence \
and nothing else: "{refusal}"
- Be concise. 2-4 short sentences for most questions. Bullet lists are \
fine for steps.
- Refer to UI elements using exact names from the manual (e.g. "Entry \
Log → Consumption Log").
- Do NOT reveal information about roles other than the user's own. \
You can mention that "Admin can do X" only if §2 lists it as a permission, \
never with operational steps from a higher-role section. (Admins themselves \
have access to all sections — answer their questions fully.)
- Output plain text. No markdown headings. No code fences.

CONTEXT (manual sections {username} is allowed to see):
{context}
"""


def _build_system_prompt(role: str, username: str = "") -> str:
    """Render the system prompt with the user's role + username + their
    role-specific refusal phrase woven in. Empty username falls back to
    "the user" so the template stays grammatical."""
    return _SYSTEM_PROMPT_TMPL.format(
        username=(username or "").strip() or "the user",
        role_label=_ROLE_LABEL.get(role, role.title() if role else "user"),
        refusal=_ROLE_REFUSAL.get(role, _ROLE_REFUSAL["store_keeper"]),
        context=_context_for_role(role) or "(manual not found on disk)",
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def health() -> tuple[bool, str]:
    """Used by the sidebar widget to render the right empty state.

    Probes Ollama LIVE on every call (via the Streamlit-cached
    `ollama_health()` helper) so users who start `ollama serve` AFTER
    Streamlit launched are picked up on the next rerun. The previous
    implementation read the module-load constant `OLLAMA_AVAILABLE`,
    which never refreshed once Streamlit was running.
    """
    try:
        ollama_health.clear()  # type: ignore[attr-defined]
    except Exception:
        pass
    if not ollama_health():
        return False, (
            f"Local AI server unreachable at `{OLLAMA_HOST}`. "
            "Start `ollama serve` locally, or set `[ollama] host = \"...\"` "
            "in Streamlit Secrets to point at a tunneled instance."
        )
    installed = list_ollama_models()
    if installed and MODEL_CHAT not in installed:
        return False, (
            f"Chat model `{MODEL_CHAT}` not pulled. Run:\n"
            f"```\nollama pull {MODEL_CHAT}\n```"
        )
    if not _manual_path().exists():
        return False, f"USER_MANUAL.md not found at {_manual_path()}."
    return True, "ready"


def answer_manual_question(
    question: str, role: str, username: str = "",
) -> Iterator[str]:
    """
    Stream the model's answer token-by-token. On failure, yield a single
    string with a friendly explanation rather than raising.

    `username` is woven into the system prompt so the model addresses the
    user by name and never tells them to "ask your Admin" when they ARE
    the Admin. Default empty for back-compat with older call sites.
    """
    ok, msg = health()
    if not ok:
        yield msg
        return

    question = (question or "").strip()
    if not question:
        yield "Type a question above and I'll answer from your section of the manual."
        return

    # Optimisation #1 — greeting fast-path. Skip the 30s prompt-eval entirely
    # for "Hi", "thanks", "ok" etc. and reply in-process.
    canned = _greeting_reply(question)
    if canned is not None:
        yield canned
        return

    system = _build_system_prompt(role, username)
    prompt = f"User question: {question}\n\nAnswer:"

    try:
        for chunk in ollama_stream(
            MODEL_CHAT,
            prompt,
            system=system,
            temperature=0.2,        # factual, not creative
            num_predict=512,
            keep_alive="30m",       # keep system-prompt KV cache warm
        ):
            yield chunk
    except RuntimeError as e:
        yield f"\n\n[Hub Assistant error: {e}]"
